# $Id: Makefile 5188 2011-12-31 09:49:52Z coelho $

# run validation in parallel
PARALLEL_VALIDATION	= 1

# explicit list of recursion directories
override D.sub	= openmp preconditions

include ../validate.mk
