
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer tp__create_buffer
#define yy_delete_buffer tp__delete_buffer
#define yy_flex_debug tp__flex_debug
#define yy_init_buffer tp__init_buffer
#define yy_flush_buffer tp__flush_buffer
#define yy_load_buffer_state tp__load_buffer_state
#define yy_switch_to_buffer tp__switch_to_buffer
#define yyin tp_in
#define yyleng tp_leng
#define yylex tp_lex
#define yylineno tp_lineno
#define yyout tp_out
#define yyrestart tp_restart
#define yytext tp_text
#define yywrap tp_wrap
#define yyalloc tp_alloc
#define yyrealloc tp_realloc
#define yyfree tp_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 36
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE tp_restart(tp_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t tp_leng;

extern FILE *tp_in, *tp_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up tp_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up tp_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via tp_restart()), so that the user can continue scanning by
	 * just pointing tp_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when tp_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t tp_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow tp_wrap()'s to do buffer switches
 * instead of setting up a fresh tp_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void tp_restart (FILE *input_file  );
void tp__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE tp__create_buffer (FILE *file,int size  );
void tp__delete_buffer (YY_BUFFER_STATE b  );
void tp__flush_buffer (YY_BUFFER_STATE b  );
void tp_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void tp_pop_buffer_state (void );

static void tp_ensure_buffer_stack (void );
static void tp__load_buffer_state (void );
static void tp__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER tp__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE tp__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE tp__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE tp__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *tp_alloc (yy_size_t  );
void *tp_realloc (void *,yy_size_t  );
void tp_free (void *  );

#define yy_new_buffer tp__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        tp_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            tp__create_buffer(tp_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        tp_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            tp__create_buffer(tp_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *tp_in , *tp_out ;

typedef int yy_state_type;

extern int tp_lineno;

int tp_lineno = 1;

extern char *tp_text;
#define yytext_ptr tp_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up tp_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	tp_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[285] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   42,   42,
       39,   39,   72,   70,   38,   51,   51,   53,   43,   70,
       70,   45,   46,   49,   69,   68,   51,   50,   47,   48,
       44,   38,   71,   37,   43,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   70,   71,   52,   41,   40,   41,   42,   42,
       39,   38,   51,   43,    0,    0,    0,    0,    0,    0,
        0,    0,   69,   68,    0,    0,    0,    0,   18,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   36,    0,    0,    0,

        0,    0,    0,   52,   41,   40,   42,   39,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       22,    0,    0,    0,    0,    0,    0,    0,    0,   16,
        0,    0,    0,    0,    0,   19,    0,    0,   33,    0,
        0,    0,    0,    0,    0,    0,   54,    0,    0,    0,
        0,   61,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   34,   23,    0,    0,   24,   17,
       10,    0,    4,   21,    0,    0,    0,    0,   26,    0,
        0,    0,    0,    0,    0,    0,   57,    0,    0,    0,
        0,   64,    0,    0,    0,   11,    0,    0,    6,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   35,    0,
        0,   29,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   12,    0,    0,    5,    8,    0,    2,
        0,    9,   25,    1,    0,   20,    0,    0,    0,    0,
        0,    0,   58,    0,    0,    0,    0,   65,    0,    0,
        0,    0,   13,    0,   32,   30,    0,   28,   55,   60,
       59,   56,   62,   67,   66,   63,   14,    0,    0,    0,
        0,    3,    0,    0,    0,    0,    0,    7,    0,    0,
       27,   15,   31,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,    1,    1,   10,
       11,    1,    1,   12,   13,   13,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   13,   15,    1,
       16,    1,    1,    1,   17,   13,   18,   19,   20,   21,
       22,   13,   23,   13,   13,   24,   25,   26,   27,   28,
       13,   29,   30,   13,   31,   13,   13,   13,   13,   13,
       32,    1,   33,    1,   13,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   13,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    2,    2,    3,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[297] =
    {   0,
        0,   33,   65,  118,   14,   15,   48,   54,   56,   58,
       19,   21,  357,  358,  354,  358,  352,  358,    0,   57,
       59,  358,  358,  358,    0,  340,  358,  358,  358,  358,
      358,  351,  358,  358,    0,   42,  295,   54,   41,   53,
      313,  312,  303,   46,  300,  292,  293,  307,   86,   39,
      298,  305,  336,  335,  358,    0,  338,    0,    0,    0,
        0,  337,  358,    0,  314,  320,    2,  307,  311,  317,
       37,  304,    0,  318,  279,  282,  291,  280,  358,  289,
      279,  287,  280,  272,  281,  279,  268,  275,  279,  274,
      279,  277,  277,  271,  267,  259,    8,  257,  264,  255,

      256,  256,  299,  358,    0,  302,    0,    0,  279,  278,
      278,  281,  272,  274,  273,  273,  276,  267,  251,  248,
      358,  243,  254,  238,  254,  249,  238,  238,  232,   84,
      235,  235,  243,  227,  233,  358,  226,  230,   88,  232,
      220,  224,  235,  236,  233,  219,  248,  244,  241,  235,
      243,  243,  239,  236,  230,  238,  205,  201,  213,  213,
      217,  202,  201,  208,  358,  358,  205,  200,  358,  358,
      358,  205,  358,  358,  194,  201,  196,  201,  358,  208,
      196,  201,  189,  198,  208,  218,  358,  213,  207,  204,
      214,  358,  209,  203,  197,  358,  173,   60,  358,  191,

      190,  193,  172,  178,  186,  185,  168,  174,  358,  182,
      166,  358,  180,  170,  190,  108,  195,  197,  187,  109,
      192,  194,  158,  358,  173,  161,  358,  358,  150,  358,
      158,  358,  358,  358,  156,  358,  149,  152,  146,  146,
      132,  131,  358,  132,  133,  120,  119,  358,  123,  109,
       94,  103,  358,  106,  105,  358,   88,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,   99,   94,   89,
       85,  358,   80,   79,   78,   59,   59,  358,   39,   35,
      358,  358,  358,  358,  172,  175,  178,  181,  184,  187,
      190,   10,  193,  196,  199,  202

    } ;

static yyconst flex_int16_t yy_def[297] =
    {   0,
      285,  285,  286,  286,  287,  287,  288,  288,  289,  289,
      290,  290,  284,  284,  284,  284,  284,  284,  291,  284,
      284,  284,  284,  284,  292,  292,  284,  284,  284,  284,
      284,  284,  284,  284,  291,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  293,  293,  284,  294,  284,  294,  295,  295,
      296,  284,  284,  291,  284,  284,  284,  284,  284,  284,
      284,  284,  292,  292,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  293,  284,  294,  284,  295,  296,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,    0,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284

    } ;

static yyconst flex_int16_t yy_nxt[416] =
    {   0,
       14,   15,   16,   17,   14,   18,   19,   20,   21,   22,
       23,   24,   73,   26,   27,   28,   54,   54,  111,   55,
       55,   33,   14,   33,   14,  284,  284,  284,  112,  284,
      284,   29,   30,   14,   15,   16,   17,   14,   18,   19,
       20,   21,   22,   23,   24,  140,   26,   27,   28,   57,
       16,   17,  284,  116,  141,   57,   16,   17,   16,   17,
       16,   17,   58,  117,   29,   30,   32,   33,   58,   34,
       60,   35,   60,   65,   66,   69,   70,   75,   83,   90,
       99,   67,   84,   71,   68,  100,   72,   78,   85,   76,
       79,  283,   91,  225,   80,  282,  281,   81,   36,   37,

       38,   39,   40,   82,   41,   42,   43,  226,   86,   44,
      280,   45,   46,   47,   48,   49,   50,   51,   52,   32,
       33,  167,   34,   96,   35,  176,   97,  241,  246,  279,
      278,  168,   98,  277,  276,  177,  242,  247,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,   36,   37,   38,   39,   40,  262,   41,   42,   43,
      261,  260,   44,  259,   45,   46,   47,   48,   49,   50,
       51,   52,   25,   25,   25,   31,   31,   31,   53,   53,
       53,   56,   56,   56,   59,   59,   59,   61,   61,   61,
       64,  258,   64,  103,  103,  103,  105,  257,  105,  107,

      256,  107,  108,  255,  108,  254,  253,  252,  251,  250,
      249,  248,  245,  244,  243,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  175,  174,  173,  172,
      171,  170,  169,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,

      149,  148,  147,  106,  104,  146,  145,  144,  143,  142,
      139,  138,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  121,  120,
      119,   74,  118,  115,  114,  113,  110,  109,   62,  106,
      104,  104,  102,  101,   95,   94,   93,   92,   89,   88,
       87,   77,   62,   74,   63,   62,  284,   13,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284
    } ;

static yyconst flex_int16_t yy_chk[416] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,  292,    1,    1,    1,    5,    6,   67,    5,
        6,   11,   11,   12,   12,    0,    0,    0,   67,    0,
        0,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,   97,    2,    2,    2,    7,
        7,    7,    0,   71,   97,    8,    8,    8,    9,    9,
       10,   10,    7,   71,    2,    2,    3,    3,    8,    3,
        9,    3,   10,   20,   20,   21,   21,   36,   39,   44,
       50,   20,   39,   21,   20,   50,   21,   38,   40,   36,
       38,  280,   44,  198,   38,  279,  277,   38,    3,    3,

        3,    3,    3,   38,    3,    3,    3,  198,   40,    3,
      276,    3,    3,    3,    3,    3,    3,    3,    3,    4,
        4,  130,    4,   49,    4,  139,   49,  216,  220,  275,
      274,  130,   49,  273,  271,  139,  216,  220,  270,  269,
      268,  257,  255,  254,  252,  251,  250,  249,  247,  246,
      245,    4,    4,    4,    4,    4,  244,    4,    4,    4,
      242,  241,    4,  240,    4,    4,    4,    4,    4,    4,
        4,    4,  285,  285,  285,  286,  286,  286,  287,  287,
      287,  288,  288,  288,  289,  289,  289,  290,  290,  290,
      291,  239,  291,  293,  293,  293,  294,  238,  294,  295,

      237,  295,  296,  235,  296,  231,  229,  226,  225,  223,
      222,  221,  219,  218,  217,  215,  214,  213,  211,  210,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  197,
      195,  194,  193,  191,  190,  189,  188,  186,  185,  184,
      183,  182,  181,  180,  178,  177,  176,  175,  172,  168,
      167,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  141,  140,  138,  137,  135,  134,
      133,  132,  131,  129,  128,  127,  126,  125,  124,  123,
      122,  120,  119,  118,  117,  116,  115,  114,  113,  112,

      111,  110,  109,  106,  103,  102,  101,  100,   99,   98,
       96,   95,   94,   93,   92,   91,   90,   89,   88,   87,
       86,   85,   84,   83,   82,   81,   80,   78,   77,   76,
       75,   74,   72,   70,   69,   68,   66,   65,   62,   57,
       54,   53,   52,   51,   48,   47,   46,   45,   43,   42,
       41,   37,   32,   26,   17,   15,   13,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int tp__flex_debug;
int tp__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *tp_text;
#line 1 "tp_lex.l"
#define YY_NO_INPUT 1
#line 4 "tp_lex.l"
/*

  $Id: tp_lex.l 23132 2016-07-04 13:06:22Z coelho $

  Copyright 1989-2016 MINES ParisTech

  This file is part of PIPS.

  PIPS is free software: you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  any later version.

  PIPS is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE.

  See the GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with PIPS.  If not, see <http://www.gnu.org/licenses/>.

*/
#ifdef HAVE_CONFIG_H
#include "pips_config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "genC.h"
#include "misc.h"
#include "tpips.h"
#include "tp_yacc.h"

/* disable echoing unmatched characters */
#define ECHO ;

/* now get the characters from a string, not from a file */
#ifndef FLEX_SCANNER

#undef input()
#define input() tpips_lex_input()
#undef unput()
#define unput(c) tpips_lex_unput(c)
void tp_restart(FILE *f){ tp_in = f;}

#else

#define YY_INPUT(buf,result,max_size)                  \
  {                                                    \
    int c = tpips_lex_input();                         \
    result = (c == '\0') ? YY_NULL : (buf[0] = c, 1);  \
  }

#endif

string tpips_unknown_string = string_undefined; // For tp_yacc.y
static bool cr_not_returned;
static char * line_to_parse;
static char * line_parsed;

void tpips_set_line_to_parse(char * line)
{
  skip_blanks(line);
  /* store line pointer */
  line_parsed = line_to_parse = line;
  cr_not_returned = true;
}

char * tpips_get_line_to_parse(void)
{
  return line_to_parse;
}

static int back = 0;

void tpips_lex_print_pos(FILE* fout)
{
  int shift = (int)((long) line_to_parse - (long)line_parsed) - back;
  fprintf(fout,
          "%s\n"
          "%*s^\n"
          "at line %d in \"%s\"\n", line_parsed, shift, "",
          tpips_current_line(), tpips_current_name());
}

static int tpips_lex_input (void)
{
  char c = *line_to_parse;
  pips_debug(9,"input char '%c'(0x%2x) from input\n", c, c);
  if (c) line_to_parse++;
  /* a fake \n is provided, to check for nargs in the syntax... */
  else if (cr_not_returned) { cr_not_returned=false; return (int) '\n'; }
  return (int) c;
}

/* string to be processed by some other lexer/parser.
 */
static char unk[2]; /* one char lines are not implicit shells */

#define RETURN(x)  pips_debug(8, "init %d\n", x); return x
#define KEYWORD(x) pips_debug(8, "key %d\n", x); BEGIN INITIAL; return x
#define LITTERAL(x)                              \
  pips_debug(8, "spc %d\n", x);                  \
  BEGIN SPC;                                     \
  return x
#define RESTART(x) pips_debug(8, "rst %d\n", x); BEGIN KEY; return x


#line 771 "<stdout>"

#define INITIAL 0
#define KEY 1
#define STR 2
#define SPC 3
#define LIT 4
#define UNK 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int tp_lex_destroy (void );

int tp_get_debug (void );

void tp_set_debug (int debug_flag  );

YY_EXTRA_TYPE tp_get_extra (void );

void tp_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *tp_get_in (void );

void tp_set_in  (FILE * in_str  );

FILE *tp_get_out (void );

void tp_set_out  (FILE * out_str  );

yy_size_t tp_get_leng (void );

char *tp_get_text (void );

int tp_get_lineno (void );

void tp_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int tp_wrap (void );
#else
extern int tp_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( tp_text, tp_leng, 1, tp_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( tp_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( tp_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, tp_in))==0 && ferror(tp_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(tp_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int tp_lex (void);

#define YY_DECL int tp_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after tp_text and tp_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 118 "tp_lex.l"


#line 959 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! tp_in )
			tp_in = stdin;

		if ( ! tp_out )
			tp_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			tp_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				tp__create_buffer(tp_in,YY_BUF_SIZE );
		}

		tp__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of tp_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 358 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 120 "tp_lex.l"
{ KEYWORD(TK_SET_ENVIRONMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 121 "tp_lex.l"
{ KEYWORD(TK_GET_ENVIRONMENT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 122 "tp_lex.l"
{ KEYWORD(TK_UNSET_ENVIRONMENT); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 123 "tp_lex.l"
{ KEYWORD(TK_OPEN); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 124 "tp_lex.l"
{ KEYWORD(TK_CREATE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 125 "tp_lex.l"
{ KEYWORD(TK_CLOSE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 126 "tp_lex.l"
{ KEYWORD(TK_CHECKPOINT); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 127 "tp_lex.l"
{ KEYWORD(TK_DELETE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 128 "tp_lex.l"
{ KEYWORD(TK_MODULE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 129 "tp_lex.l"
{ KEYWORD(TK_MAKE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 130 "tp_lex.l"
{ KEYWORD(TK_APPLY); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 131 "tp_lex.l"
{ KEYWORD(TK_CAPPLY); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 132 "tp_lex.l"
{ KEYWORD(TK_DISPLAY); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 133 "tp_lex.l"
{ KEYWORD(TK_ACTIVATE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 134 "tp_lex.l"
{ KEYWORD(TK_GET_PROPERTY); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 135 "tp_lex.l"
{ KEYWORD(TK_GET_PROPERTY); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 136 "tp_lex.l"
{ KEYWORD(TK_INFO); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 137 "tp_lex.l"
{ KEYWORD(TK_CDIR); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 138 "tp_lex.l"
{ KEYWORD(TK_PWD); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 139 "tp_lex.l"
{ KEYWORD(TK_SOURCE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 140 "tp_lex.l"
{ KEYWORD(TK_QUIT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 141 "tp_lex.l"
{ KEYWORD(TK_QUIT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 142 "tp_lex.l"
{ KEYWORD(TK_EXIT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 143 "tp_lex.l"
{ KEYWORD(TK_HELP); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 144 "tp_lex.l"
{ KEYWORD(TK_REMOVE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 145 "tp_lex.l"
{ KEYWORD(TK_SHOW); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 146 "tp_lex.l"
{ KEYWORD(TK_CHECKACTIVE); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 147 "tp_lex.l"
{ KEYWORD(TK_VERSION); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 148 "tp_lex.l"
{ KEYWORD(TK_TOUCH); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 149 "tp_lex.l"
{ KEYWORD(TK_TIMEOUT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 151 "tp_lex.l"
{ LITTERAL(TK_SET_PROPERTY); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 152 "tp_lex.l"
{ LITTERAL(TK_SET_PROPERTY); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 153 "tp_lex.l"
{ LITTERAL(TK_SET_PROPERTY); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 154 "tp_lex.l"
{ LITTERAL(TK_ECHO); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 155 "tp_lex.l"
{ LITTERAL(TK_SHELL); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 156 "tp_lex.l"
{ LITTERAL(TK_SHELL); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 157 "tp_lex.l"
{ LITTERAL(TK_SHELL); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 159 "tp_lex.l"
/* skip blanks... */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 161 "tp_lex.l"
{ tp_lval.name = strdup(concatenate(unk, tp_text, NULL));
   tpips_unknown_string=strdup(tp_text);
   KEYWORD(TK_UNKNOWN); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 165 "tp_lex.l"
{ BEGIN LIT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 166 "tp_lex.l"
{
   back = strlen(tp_text);
   tp_error("Space expected after initial keyword.\n");
   back = 0;
 }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 171 "tp_lex.l"
{ tp_lval.name = strdup(tp_text); RETURN(TK_LINE); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 172 "tp_lex.l"
{ BEGIN INITIAL;
   /* skip comments... (not for echo, shell set). */}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 174 "tp_lex.l"
{ unk[0]=tp_text[0]; unk[1]='\0'; BEGIN UNK; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 176 "tp_lex.l"
{ RETURN(TK_OPENPAREN); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 177 "tp_lex.l"
{ RETURN(TK_CLOSEPAREN); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 179 "tp_lex.l"
{ RETURN(TK_OPENPAREN); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 180 "tp_lex.l"
{ RETURN(TK_CLOSEPAREN); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 182 "tp_lex.l"
{ RETURN(TK_COMMA); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 183 "tp_lex.l"
{ RETURN(TK_EQUAL); }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 185 "tp_lex.l"
{ RESTART(TK_ENDOFLINE); }
	YY_BREAK
case YY_STATE_EOF(LIT):
case YY_STATE_EOF(INITIAL):
#line 186 "tp_lex.l"
{ RESTART(TK_ENDOFLINE); }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 188 "tp_lex.l"
{
  // string contents without surrounding double quotes
  // no attempt at managing escaping double quotes
  tp_lval.name = strdup(tp_text);
  tp_lval.name[strlen(tp_text)-1] = '\0';
  BEGIN INITIAL; RETURN(TK_A_STRING);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 194 "tp_lex.l"
{ BEGIN STR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 196 "tp_lex.l"
{ RETURN(TK_OWNER_ALL); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 197 "tp_lex.l"
{ RETURN(TK_OWNER_ALLFUNC); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 198 "tp_lex.l"
{ RETURN(TK_OWNER_PROGRAM); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 199 "tp_lex.l"
{ RETURN(TK_OWNER_MAIN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 200 "tp_lex.l"
{ RETURN(TK_OWNER_MODULE); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 201 "tp_lex.l"
{ RETURN(TK_OWNER_CALLERS); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 202 "tp_lex.l"
{ RETURN(TK_OWNER_CALLEES); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 204 "tp_lex.l"
{ RETURN(TK_OWNER_ALL); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 205 "tp_lex.l"
{ RETURN(TK_OWNER_ALLFUNC); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 206 "tp_lex.l"
{ RETURN(TK_OWNER_PROGRAM); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 207 "tp_lex.l"
{ RETURN(TK_OWNER_MAIN); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 208 "tp_lex.l"
{ RETURN(TK_OWNER_MODULE); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 209 "tp_lex.l"
{ RETURN(TK_OWNER_CALLERS); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 210 "tp_lex.l"
{ RETURN(TK_OWNER_CALLEES); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 212 "tp_lex.l"
{ tp_lval.ival = atoi(tp_text); RETURN(TK_INT); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 214 "tp_lex.l"
{
  tp_lval.name = strdup(tp_text);
  RETURN(TK_NAME);
 }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 218 "tp_lex.l"
{ pips_user_warning("Unrecognized character \"%s\"\n",tp_text); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 220 "tp_lex.l"
ECHO;
	YY_BREAK
#line 1419 "<stdout>"
case YY_STATE_EOF(KEY):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(SPC):
case YY_STATE_EOF(UNK):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed tp_in at a new source and called
			 * tp_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = tp_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( tp_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * tp_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of tp_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					tp_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			tp_restart(tp_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > (yy_size_t)YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) tp_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 284);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					tp_restart(tp_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( tp_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve tp_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void tp_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        tp_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            tp__create_buffer(tp_in,YY_BUF_SIZE );
	}

	tp__init_buffer(YY_CURRENT_BUFFER,input_file );
	tp__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void tp__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		tp_pop_buffer_state();
	 *		tp_push_buffer_state(new_buffer);
     */
	tp_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	tp__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (tp_wrap()) processing, but the only time this flag
	 * is looked at is after tp_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void tp__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	tp_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE tp__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) tp_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in tp__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) tp_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in tp__create_buffer()" );

	b->yy_is_our_buffer = 1;

	tp__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with tp__create_buffer()
 * 
 */
    void tp__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		tp_free((void *) b->yy_ch_buf  );

	tp_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a tp_restart() or at EOF.
 */
    static void tp__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	tp__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then tp__init_buffer was _probably_
     * called from tp_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void tp__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		tp__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void tp_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	tp_ensure_buffer_stack();

	/* This block is copied from tp__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from tp__switch_to_buffer. */
	tp__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void tp_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	tp__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		tp__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void tp_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)tp_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in tp_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)tp_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in tp_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE tp__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) tp_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in tp__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	tp__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to tp_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       tp__scan_bytes() instead.
 */
YY_BUFFER_STATE tp__scan_string (yyconst char * yystr )
{
    
	return tp__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to tp_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE tp__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) tp_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in tp__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = tp__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in tp__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up tp_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		tp_text[tp_leng] = (yy_hold_char); \
		(yy_c_buf_p) = tp_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		tp_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int tp_get_lineno  (void)
{
        
    return tp_lineno;
}

/** Get the input stream.
 * 
 */
FILE *tp_get_in  (void)
{
        return tp_in;
}

/** Get the output stream.
 * 
 */
FILE *tp_get_out  (void)
{
        return tp_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t tp_get_leng  (void)
{
        return tp_leng;
}

/** Get the current token.
 * 
 */

char *tp_get_text  (void)
{
        return tp_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void tp_set_lineno (int  line_number )
{
    
    tp_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see tp__switch_to_buffer
 */
void tp_set_in (FILE *  in_str )
{
        tp_in = in_str ;
}

void tp_set_out (FILE *  out_str )
{
        tp_out = out_str ;
}

int tp_get_debug  (void)
{
        return tp__flex_debug;
}

void tp_set_debug (int  bdebug )
{
        tp__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from tp_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    tp_in = stdin;
    tp_out = stdout;
#else
    tp_in = (FILE *) 0;
    tp_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * tp_lex_init()
     */
    return 0;
}

/* tp_lex_destroy is for both reentrant and non-reentrant scanners. */
int tp_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		tp__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		tp_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	tp_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * tp_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *tp_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *tp_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void tp_free (void * ptr )
{
	free( (char *) ptr );	/* see tp_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 220 "tp_lex.l"



int tp_wrap(void){ return 1; }

void tp_init_lex(void)
{
  BEGIN KEY;
#ifdef FLEX_SCANNER
  yy_init = 1;
#endif
}

void tp_error(const char * s)
{
  tpips_init(); /* needed for user error... */
  tpips_lex_print_pos(stderr);
  pips_user_error("%s\n", s);
}

