
#line 3 "<stdout>"

#define YY_NO_INPUT 1
#define IN_PIPS 1
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer comment2pragma_create_buffer
#define yy_delete_buffer comment2pragma_delete_buffer
#define yy_flex_debug comment2pragma_flex_debug
#define yy_init_buffer comment2pragma_init_buffer
#define yy_flush_buffer comment2pragma_flush_buffer
#define yy_load_buffer_state comment2pragma_load_buffer_state
#define yy_switch_to_buffer comment2pragma_switch_to_buffer
#define yyin comment2pragmain
#define yyleng comment2pragmaleng
#define yylex comment2pragmalex
#define yylineno comment2pragmalineno
#define yyout comment2pragmaout
#define yyrestart comment2pragmarestart
#define yytext comment2pragmatext
#define yywrap comment2pragmawrap
#define yyalloc comment2pragmaalloc
#define yyrealloc comment2pragmarealloc
#define yyfree comment2pragmafree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 36
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE comment2pragmarestart(comment2pragmain  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t comment2pragmaleng;

extern FILE *comment2pragmain, *comment2pragmaout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up comment2pragmatext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up comment2pragmatext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via comment2pragmarestart()), so that the user can continue scanning by
	 * just pointing comment2pragmain at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when comment2pragmatext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t comment2pragmaleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow comment2pragmawrap()'s to do buffer switches
 * instead of setting up a fresh comment2pragmain.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void comment2pragmarestart (FILE *input_file  );
void comment2pragma_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE comment2pragma_create_buffer (FILE *file,int size  );
void comment2pragma_delete_buffer (YY_BUFFER_STATE b  );
void comment2pragma_flush_buffer (YY_BUFFER_STATE b  );
void comment2pragmapush_buffer_state (YY_BUFFER_STATE new_buffer  );
void comment2pragmapop_buffer_state (void );

static void comment2pragmaensure_buffer_stack (void );
static void comment2pragma_load_buffer_state (void );
static void comment2pragma_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER comment2pragma_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE comment2pragma_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE comment2pragma_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE comment2pragma_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *comment2pragmaalloc (yy_size_t  );
void *comment2pragmarealloc (void *,yy_size_t  );
void comment2pragmafree (void *  );

#define yy_new_buffer comment2pragma_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        comment2pragmaensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            comment2pragma_create_buffer(comment2pragmain,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        comment2pragmaensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            comment2pragma_create_buffer(comment2pragmain,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define comment2pragmawrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *comment2pragmain , *comment2pragmaout ;

typedef int yy_state_type;

extern int comment2pragmalineno;

int comment2pragmalineno = 1;

extern char *comment2pragmatext;
#define yytext_ptr comment2pragmatext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up comment2pragmatext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	comment2pragmaleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[95] =
    {   0,
        0,    0,    0,    0,    5,    5,    0,    0,    0,    0,
        0,    0,    1,    1,    0,    0,    0,    0,    0,    0,
       20,   19,   18,   17,   15,   18,   19,   13,   19,    5,
       10,    9,   19,    1,   10,    2,   19,   19,   14,   16,
        0,    0,   13,    0,    0,    5,    0,    9,    0,    0,
        1,    2,    0,    0,   14,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   11,    0,
        0,    0,    7,    0,    0,    0,   12,    0,    0,    8,
        0,    0,    6,    0,    3,    0,    3,    0,    4,    3,
        4,    0,    4,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    5,    1,    6,    1,    1,
        1,    7,    1,    1,    1,    1,    1,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,    1,    1,
        1,    1,    1,    1,    1,    1,    7,    1,    9,    1,
        1,    1,    1,    1,    1,    1,   10,    1,   11,   12,
        1,    1,   13,   14,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,    8,    7,    1,

       15,    1,    1,    1,    1,    1,    8,    8,   16,    8,
       17,   18,    1,    1,   19,   20,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[21] =
    {   0,
        1,    2,    3,    4,    1,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[110] =
    {   0,
        0,    0,    6,    7,    2,   10,   12,   14,  187,  186,
       16,   17,   20,   24,   28,   32,   36,   38,  187,  186,
      188,  193,  193,  193,  193,   21,  184,  193,   32,    0,
       40,    0,   41,    0,  193,    0,  178,  182,  193,  193,
       29,  178,  193,   40,   39,    0,  171,    0,   45,   43,
        0,    0,   58,  168,  193,   52,   56,   61,   55,   60,
      158,  160,   64,   67,   65,    0,   69,   77,  193,  153,
       74,   80,  193,    0,   81,   79,  193,    0,   86,  193,
       88,   92,  193,    0,   40,   90,  143,   97,  103,  142,
       76,  104,   60,  193,  112,  117,  122,  127,  132,  137,

      142,  147,  152,  157,  159,  164,  169,  174,  179
    } ;

static yyconst flex_int16_t yy_def[110] =
    {   0,
       95,   96,   97,   97,   98,   98,   95,   95,   95,   95,
       97,   97,   99,   99,   95,   95,   95,   95,  100,  100,
       94,   94,   94,   94,   94,   94,  101,   94,   94,  102,
       94,  103,   94,  104,   94,  105,   94,  106,   94,   94,
       94,  101,   94,   94,   94,  102,   94,  103,   94,   94,
      104,  105,   94,  106,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,  107,   94,   94,   94,   94,
       94,   94,   94,  108,   94,   94,   94,  109,   94,   94,
       94,   94,   94,  109,   94,   94,   94,   94,   94,   94,
       94,   94,   94,    0,   94,   94,   94,   94,   94,   94,

       94,   94,   94,   94,   94,   94,   94,   94,   94
    } ;

static yyconst flex_int16_t yy_nxt[214] =
    {   0,
       94,   94,   24,   25,   22,   22,   25,   26,   28,   28,
       29,   29,   22,   22,   31,   32,   31,   32,   28,   28,
       29,   29,   22,   22,   40,   22,   22,   22,   41,   22,
       35,   32,   40,   36,   35,   32,   41,   36,   37,   32,
       37,   32,   44,   47,   45,   87,   47,   88,   44,   56,
       45,   49,   57,   50,   59,   56,   60,   49,   57,   50,
       59,   61,   60,   62,   63,   53,   66,   93,   67,   62,
       63,   64,   66,   65,   67,   70,   71,   64,   72,   65,
       74,   70,   71,   93,   72,   78,   74,   75,   79,   76,
       81,   78,   82,   75,   79,   76,   81,   84,   82,   85,

       86,   89,   87,   84,   88,   85,   86,   89,   91,   91,
       92,   92,   22,   22,   22,   22,   22,   23,   23,   23,
       23,   23,   27,   27,   27,   27,   27,   30,   30,   30,
       30,   30,   34,   34,   34,   34,   34,   38,   38,   38,
       38,   38,   42,   42,   42,   42,   42,   46,   46,   90,
       90,   46,   48,   48,   77,   48,   48,   51,   51,   52,
       52,   69,   68,   52,   54,   54,   54,   54,   54,   73,
       55,   73,   73,   73,   80,   58,   80,   80,   80,   83,
       43,   83,   83,   83,   55,   53,   43,   94,   39,   39,
       33,   33,   21,   94,   94,   94,   94,   94,   94,   94,

       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94
    } ;

static yyconst flex_int16_t yy_chk[214] =
    {   0,
        0,    0,    2,    2,    5,    5,    2,    2,    3,    4,
        3,    4,    6,    6,    7,    7,    8,    8,   11,   12,
       11,   12,   13,   13,   26,   13,   14,   14,   26,   14,
       15,   15,   41,   15,   16,   16,   41,   16,   17,   17,
       18,   18,   29,   31,   29,   85,   31,   85,   29,   44,
       29,   33,   45,   33,   49,   44,   50,   33,   45,   33,
       49,   53,   50,   56,   57,   53,   59,   93,   60,   56,
       57,   58,   59,   58,   60,   63,   64,   58,   65,   58,
       67,   63,   64,   91,   65,   71,   67,   68,   72,   68,
       75,   71,   76,   68,   72,   68,   75,   79,   76,   81,

       82,   86,   88,   79,   88,   81,   82,   86,   89,   92,
       89,   92,   95,   95,   95,   95,   95,   96,   96,   96,
       96,   96,   97,   97,   97,   97,   97,   98,   98,   98,
       98,   98,   99,   99,   99,   99,   99,  100,  100,  100,
      100,  100,  101,  101,  101,  101,  101,  102,  102,   90,
       87,  102,  103,  103,   70,  103,  103,  104,  104,  105,
      105,   62,   61,  105,  106,  106,  106,  106,  106,  107,
       54,  107,  107,  107,  108,   47,  108,  108,  108,  109,
       42,  109,  109,  109,   38,   37,   27,   21,   20,   19,
       10,    9,   94,   94,   94,   94,   94,   94,   94,   94,

       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int comment2pragma_flex_debug;
int comment2pragma_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *comment2pragmatext;
#line 1 "comment2pragma.l"
#line 2 "comment2pragma.l"
#include "defines-local.h"

static statement current_statement = statement_undefined;

static char *directive_txt = NULL;
static char *comment_txt = NULL;

static void directive_start(int type);
static void directive_reset(void);
static void append(char **buffer);
static void clean_buffer(char **buffer);
static void end_directive(void);
static void end_comment(void);

static int directive_syntaxe = -1;
static int directive_type = -1;

#define DIRECTIVE_STEP 0
#define DIRECTIVE_OMP 1

#define YY_NO_INPUT 1
/*
Attention PIPS supprime les blancs en début de commentaire en syntaxe libre, et insère un saut de ligne supplémentaire :
|     !txt1
|     !txt2
devient :
|!txt1
|
|!txt2
|
*/



#line 591 "<stdout>"

#define INITIAL 0
#define comment_fixe 1
#define directive_fixe 2
#define directive_fixe_comment 3
#define directive_fixe_continuation 4
#define comment_libre 5
#define directive_libre 6
#define directive_libre_comment 7
#define directive_libre_continuation 8
#define other_line 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int comment2pragmalex_destroy (void );

int comment2pragmaget_debug (void );

void comment2pragmaset_debug (int debug_flag  );

YY_EXTRA_TYPE comment2pragmaget_extra (void );

void comment2pragmaset_extra (YY_EXTRA_TYPE user_defined  );

FILE *comment2pragmaget_in (void );

void comment2pragmaset_in  (FILE * in_str  );

FILE *comment2pragmaget_out (void );

void comment2pragmaset_out  (FILE * out_str  );

yy_size_t comment2pragmaget_leng (void );

char *comment2pragmaget_text (void );

int comment2pragmaget_lineno (void );

void comment2pragmaset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int comment2pragmawrap (void );
#else
extern int comment2pragmawrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( comment2pragmatext, comment2pragmaleng, 1, comment2pragmaout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( comment2pragmain )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( comment2pragmain ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, comment2pragmain))==0 && ferror(comment2pragmain)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(comment2pragmain); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int comment2pragmalex (void);

#define YY_DECL int comment2pragmalex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after comment2pragmatext and comment2pragmaleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( comment2pragmaleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(comment2pragmatext[comment2pragmaleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 54 "comment2pragma.l"


 /*
  Directive à syntaxe libre
 */
#line 789 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! comment2pragmain )
			comment2pragmain = stdin;

		if ( ! comment2pragmaout )
			comment2pragmaout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			comment2pragmaensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				comment2pragma_create_buffer(comment2pragmain,YY_BUF_SIZE );
		}

		comment2pragma_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of comment2pragmatext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 95 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 193 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 59 "comment2pragma.l"
{
  append(&directive_txt); // ajout du texte de la directive
  BEGIN(directive_libre_comment);
 }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "comment2pragma.l"
{ // détection d'une continuation du texte de la directive sur la ligne suivante
  BEGIN(directive_libre_continuation);
 }
	YY_BREAK
// controle de la continuation
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 69 "comment2pragma.l"
{
    if (directive_type != DIRECTIVE_OMP)
      yy_fatal_error("erreur continuation omp libre\n");
    BEGIN(directive_libre);
  }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 74 "comment2pragma.l"
{
    if (directive_type != DIRECTIVE_STEP)
      yy_fatal_error("erreur continuation omp libre\n");
    BEGIN(directive_libre);
  }
	YY_BREAK

/*
  Directive à syntaxe fixe
 */
case 5:
YY_RULE_SETUP
#line 84 "comment2pragma.l"
{
  append(&directive_txt); // ajout du texte de la directive
  BEGIN(directive_fixe_comment);
 }
	YY_BREAK
case 6:
/* rule 6 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up comment2pragmatext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up comment2pragmatext again */
YY_RULE_SETUP
#line 89 "comment2pragma.l"
{ // détection d'une continuation du texte de la directive sur la ligne suivante
  BEGIN(directive_fixe_continuation);
 }
	YY_BREAK
// controle de la continuation
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 94 "comment2pragma.l"
{
    if (directive_type != DIRECTIVE_OMP)
      yy_fatal_error("erreur continuation omp fixe\n");
    BEGIN(directive_fixe);
  }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 99 "comment2pragma.l"
{
    if (directive_type != DIRECTIVE_STEP)
      yy_fatal_error("erreur continuation step fixe\n");
    BEGIN(directive_fixe);
  }
	YY_BREAK

/*
   Collecte d'un commentaire porté par une directive
 */
case 9:
YY_RULE_SETUP
#line 109 "comment2pragma.l"
{
  append(&comment_txt);
 }
	YY_BREAK
/*
   Détection de la fin d'une directive et de son commentaire associé éventuel
 */
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 116 "comment2pragma.l"
{
  append(&comment_txt);

  end_directive();

  directive_reset();
  BEGIN(INITIAL);
 }
	YY_BREAK
/*
   Identification d'une nouvelle directive
 */

case 11:
YY_RULE_SETUP
#line 129 "comment2pragma.l"
{
    directive_start(DIRECTIVE_OMP);
  }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 132 "comment2pragma.l"
{
    directive_start(DIRECTIVE_STEP);
  }
	YY_BREAK

/*
   Identification des commentaires et autres lignes
 */
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 140 "comment2pragma.l"
{
  append(&comment_txt);
  end_comment();
  clean_buffer(&comment_txt);
  BEGIN(INITIAL);
 }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 146 "comment2pragma.l"
{
  append(&comment_txt);
  end_comment();
  clean_buffer(&comment_txt);
  BEGIN(INITIAL);
 }
	YY_BREAK

case 15:
YY_RULE_SETUP
#line 155 "comment2pragma.l"
{
     BEGIN(comment_fixe);
     yymore();
   }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 159 "comment2pragma.l"
{
     BEGIN(comment_libre);
     yymore();
   }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 163 "comment2pragma.l"
{
     append(&comment_txt);
     end_comment();
     clean_buffer(&comment_txt);
   }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 168 "comment2pragma.l"
{
     BEGIN(other_line);
     yymore();
   }
	YY_BREAK

case 19:
YY_RULE_SETUP
#line 174 "comment2pragma.l"
ECHO;
	YY_BREAK
#line 1071 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment_fixe):
case YY_STATE_EOF(directive_fixe):
case YY_STATE_EOF(directive_fixe_comment):
case YY_STATE_EOF(directive_fixe_continuation):
case YY_STATE_EOF(comment_libre):
case YY_STATE_EOF(directive_libre):
case YY_STATE_EOF(directive_libre_comment):
case YY_STATE_EOF(directive_libre_continuation):
case YY_STATE_EOF(other_line):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed comment2pragmain at a new source and called
			 * comment2pragmalex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = comment2pragmain;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( comment2pragmawrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * comment2pragmatext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of comment2pragmalex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					comment2pragmarealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ((int)  number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			comment2pragmarestart(comment2pragmain  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > (yy_size_t)YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) comment2pragmarealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 95 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 95 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 94);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					comment2pragmarestart(comment2pragmain );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( comment2pragmawrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve comment2pragmatext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void comment2pragmarestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        comment2pragmaensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            comment2pragma_create_buffer(comment2pragmain,YY_BUF_SIZE );
	}

	comment2pragma_init_buffer(YY_CURRENT_BUFFER,input_file );
	comment2pragma_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void comment2pragma_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		comment2pragmapop_buffer_state();
	 *		comment2pragmapush_buffer_state(new_buffer);
     */
	comment2pragmaensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	comment2pragma_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (comment2pragmawrap()) processing, but the only time this flag
	 * is looked at is after comment2pragmawrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void comment2pragma_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	comment2pragmain = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE comment2pragma_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) comment2pragmaalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in comment2pragma_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) comment2pragmaalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in comment2pragma_create_buffer()" );

	b->yy_is_our_buffer = 1;

	comment2pragma_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with comment2pragma_create_buffer()
 * 
 */
    void comment2pragma_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		comment2pragmafree((void *) b->yy_ch_buf  );

	comment2pragmafree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a comment2pragmarestart() or at EOF.
 */
    static void comment2pragma_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	comment2pragma_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then comment2pragma_init_buffer was _probably_
     * called from comment2pragmarestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void comment2pragma_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		comment2pragma_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void comment2pragmapush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	comment2pragmaensure_buffer_stack();

	/* This block is copied from comment2pragma_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from comment2pragma_switch_to_buffer. */
	comment2pragma_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void comment2pragmapop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	comment2pragma_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		comment2pragma_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void comment2pragmaensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)comment2pragmaalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in comment2pragmaensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)comment2pragmarealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in comment2pragmaensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE comment2pragma_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) comment2pragmaalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in comment2pragma_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	comment2pragma_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to comment2pragmalex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       comment2pragma_scan_bytes() instead.
 */
YY_BUFFER_STATE comment2pragma_scan_string (yyconst char * yystr )
{
    
	return comment2pragma_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to comment2pragmalex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE comment2pragma_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) comment2pragmaalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in comment2pragma_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = comment2pragma_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in comment2pragma_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up comment2pragmatext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		comment2pragmatext[comment2pragmaleng] = (yy_hold_char); \
		(yy_c_buf_p) = comment2pragmatext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		comment2pragmaleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int comment2pragmaget_lineno  (void)
{
        
    return comment2pragmalineno;
}

/** Get the input stream.
 * 
 */
FILE *comment2pragmaget_in  (void)
{
        return comment2pragmain;
}

/** Get the output stream.
 * 
 */
FILE *comment2pragmaget_out  (void)
{
        return comment2pragmaout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t comment2pragmaget_leng  (void)
{
        return comment2pragmaleng;
}

/** Get the current token.
 * 
 */

char *comment2pragmaget_text  (void)
{
        return comment2pragmatext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void comment2pragmaset_lineno (int  line_number )
{
    
    comment2pragmalineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see comment2pragma_switch_to_buffer
 */
void comment2pragmaset_in (FILE *  in_str )
{
        comment2pragmain = in_str ;
}

void comment2pragmaset_out (FILE *  out_str )
{
        comment2pragmaout = out_str ;
}

int comment2pragmaget_debug  (void)
{
        return comment2pragma_flex_debug;
}

void comment2pragmaset_debug (int  bdebug )
{
        comment2pragma_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from comment2pragmalex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    comment2pragmain = stdin;
    comment2pragmaout = stdout;
#else
    comment2pragmain = (FILE *) 0;
    comment2pragmaout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * comment2pragmalex_init()
     */
    return 0;
}

/* comment2pragmalex_destroy is for both reentrant and non-reentrant scanners. */
int comment2pragmalex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		comment2pragma_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		comment2pragmapop_buffer_state();
	}

	/* Destroy the stack itself. */
	comment2pragmafree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * comment2pragmalex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *comment2pragmaalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *comment2pragmarealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void comment2pragmafree (void * ptr )
{
	free( (char *) ptr );	/* see comment2pragmarealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 174 "comment2pragma.l"



static void directive_start(int type)
{
  directive_type = type;

  switch (YY_START)
    {
    case comment_fixe:
      directive_syntaxe = directive_fixe;
      BEGIN(directive_fixe);
      break;
    case comment_libre:
      directive_syntaxe = directive_libre;
      BEGIN(directive_libre);
      break;
    default:
      yy_fatal_error("erreur syntaxe\n");
    }
}

static void directive_reset(void)
{
  clean_buffer(&directive_txt);
  clean_buffer(&comment_txt);
  directive_syntaxe = -1;
  directive_type = -1;
}

static void append(char **buffer)
{
  if (*buffer == NULL)
    *buffer = strdup(comment2pragmatext);
  else
    {
      *buffer = realloc(*buffer, sizeof(*buffer) * (strlen(*buffer) + comment2pragmaleng));
      *buffer = strncat(*buffer, comment2pragmatext, comment2pragmaleng);
    }
}

static void clean_buffer(char **buffer)
{
  if(*buffer != NULL)
    {
      free(*buffer);
      *buffer = NULL;
    }
}

static void remove_blank(void)
{
  char *dest;
  char *src;

  dest = directive_txt;
  for(src=directive_txt; *src !='\0'; src++)
    if (*src != ' ' && *src != '\t')
      {
	*dest=*src;
	    dest++;
      }
  *dest = '\0';
}

static char *get_directive_type(void)
{
  switch (directive_type)
    {
    case  DIRECTIVE_STEP:
      return strdup("step");
      break;
    case DIRECTIVE_OMP:
      return strdup("omp");
      break;
    default:
      return NULL;
      break;
    }
}


static void end_comment(void)
{
  if (!statement_undefined_p(current_statement))
    {
      pips_debug(2,"COMMENTAIRE_TXT-> \"%s\"\n", comment_txt);
      append_comments_to_statement(current_statement, comment_txt);
    }
  else
    {
      ifdebug(1)
	{
	  if (comment_txt !=NULL)
	    pips_debug(1,"%s :%s",(YY_START==other_line)?"OTHER_LINE":"COMMENT", comment_txt);
	  else
	    pips_debug(1,"\n");
	}
    }
}

static void end_directive(void)
{
  string directive_type = get_directive_type();

  // suppression du saut de ligne
  comment_txt[strlen(comment_txt)-1]='\0';

  if (directive_syntaxe == directive_fixe)
    remove_blank();

  pips_debug(2,"DIRECTIVE-> %s \"%s\"\n", directive_type, directive_txt);
  pips_debug(2,"\tCOMMENTAIRE_DIR-> \"%s\"\n", comment_txt);

  if(!statement_undefined_p(current_statement))
    {
      extensions_extension(statement_extensions(current_statement))=gen_nreverse(extensions_extension(statement_extensions(current_statement)));
      add_pragma_str_to_statement(current_statement, strdup(concatenate(directive_type,directive_txt,NULL)), false);
      extensions_extension(statement_extensions(current_statement))=gen_nreverse(extensions_extension(statement_extensions(current_statement)));

      if (strlen(comment_txt))
	{
	  if (!empty_comments_p(statement_comments(current_statement)))
	    {
	      free(statement_comments(current_statement));
	      statement_comments(current_statement) = string_undefined;
	    }
	  append_comments_to_statement(current_statement, comment_txt);
	}
    }
  else
    {
      pips_debug(1, "DIRECTIVE in decls_txt\n");
    }

  free(directive_type);
}

/*
 * For fortran programs
 * converting comments into pragmas
 *
*/

void step_comment2pragma_handle(statement stmt)
{
  pips_debug(1,"begin\n");
  if(!statement_undefined_p(stmt))
    {
      string comment = statement_comments(stmt);

      if (!empty_comments_p(comment))
	{
	  pips_assert("statement undefined", statement_undefined_p(current_statement));
	  current_statement = stmt;
	  statement_comments(stmt) = string_undefined;

	  pips_debug(1,"Comment txt : begin scan\n");
	  comment2pragma_scan_string(comment);
	  comment2pragmalex();
	  pips_debug(1,"Comment txt : end scan\n");

	  free(comment);
	  current_statement = statement_undefined;
	}
      else
	{
	  pips_debug(1,"Comment txt : Empty\n");
	}
    }
  else
    {
      string decls_txt = code_decls_text(entity_code(get_current_module_entity()));
      if (!empty_comments_p(decls_txt))
	{
	  pips_debug(1,"Declaration txt : begin scan\n");
	  comment2pragma_scan_string(decls_txt);
	  comment2pragmalex();
	  pips_debug(1,"Declaration txt : end scan\n");
	}
      else
	{
	  pips_debug(1,"Declaration txt : Empty\n");
	}
    }
  pips_debug(1,"end\n");
}

