/*
Runtime API intrinsic declaration (generated from step_api.h)
Included by src/Libs/bootstrap/bootstrap.c
*/
{RT_STEP_alltoall_full_interlaced, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_alltoall_full, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_alltoall_partial_interlaced, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_alltoall_partial, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_alltoall, 2, overloaded_to_void_type, 0, 0},
{RT_STEP_barrier, 0, overloaded_to_void_type, 0, 0},
{RT_STEP_compute_loopslices, 4, overloaded_to_void_type, 0, 0},
{RT_STEP_construct_begin, 1, overloaded_to_void_type, 0, 0},
{RT_STEP_construct_end, 1, overloaded_to_void_type, 0, 0},
{RT_STEP_finalize, 0, overloaded_to_void_type, 0, 0},
{RT_STEP_flush, 0, overloaded_to_void_type, 0, 0},
{RT_STEP_get_commsize, 1, overloaded_to_void_type, 0, 0},
{RT_STEP_get_loopbounds, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_get_rank, 1, overloaded_to_void_type, 0, 0},
{RT_STEP_init_arrayregions, 4, overloaded_to_void_type, 0, 0},
{RT_STEP_init_c_order, 0, overloaded_to_void_type, 0, 0},
{RT_STEP_init_fortran_order, 0, overloaded_to_void_type, 0, 0},
{RT_STEP_initreduction, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_reduction, 1, overloaded_to_void_type, 0, 0},
{RT_STEP_register_alltoall_partial, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_set_interlaced_sendregions, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_set_recvregions, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_set_reduction_sendregions, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_set_sendregions, 3, overloaded_to_void_type, 0, 0},
{RT_STEP_timer_dump, 4, overloaded_to_void_type, 0, 0},
{RT_STEP_timer_event, 1, overloaded_to_void_type, 0, 0},
{RT_STEP_timer_finalize, 1, overloaded_to_void_type, 0, 0},
{RT_STEP_timer_init, 1, overloaded_to_void_type, 0, 0},
{RT_STEP_timer_reset, 1, overloaded_to_void_type, 0, 0},
/* Runtime API intrinsic declaration (end) */
