
#line 3 "<stdout>"

#define YY_NO_INPUT 1
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer step_lexer_create_buffer
#define yy_delete_buffer step_lexer_delete_buffer
#define yy_flex_debug step_lexer_flex_debug
#define yy_init_buffer step_lexer_init_buffer
#define yy_flush_buffer step_lexer_flush_buffer
#define yy_load_buffer_state step_lexer_load_buffer_state
#define yy_switch_to_buffer step_lexer_switch_to_buffer
#define yyin step_lexerin
#define yyleng step_lexerleng
#define yylex step_lexerlex
#define yylineno step_lexerlineno
#define yyout step_lexerout
#define yyrestart step_lexerrestart
#define yytext step_lexertext
#define yywrap step_lexerwrap
#define yyalloc step_lexeralloc
#define yyrealloc step_lexerrealloc
#define yyfree step_lexerfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 36
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE step_lexerrestart(step_lexerin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t step_lexerleng;

extern FILE *step_lexerin, *step_lexerout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up step_lexertext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up step_lexertext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via step_lexerrestart()), so that the user can continue scanning by
	 * just pointing step_lexerin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when step_lexertext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t step_lexerleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow step_lexerwrap()'s to do buffer switches
 * instead of setting up a fresh step_lexerin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void step_lexerrestart (FILE *input_file  );
void step_lexer_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE step_lexer_create_buffer (FILE *file,int size  );
void step_lexer_delete_buffer (YY_BUFFER_STATE b  );
void step_lexer_flush_buffer (YY_BUFFER_STATE b  );
void step_lexerpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void step_lexerpop_buffer_state (void );

static void step_lexerensure_buffer_stack (void );
static void step_lexer_load_buffer_state (void );
static void step_lexer_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER step_lexer_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE step_lexer_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE step_lexer_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE step_lexer_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *step_lexeralloc (yy_size_t  );
void *step_lexerrealloc (void *,yy_size_t  );
void step_lexerfree (void *  );

#define yy_new_buffer step_lexer_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        step_lexerensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            step_lexer_create_buffer(step_lexerin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        step_lexerensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            step_lexer_create_buffer(step_lexerin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define step_lexerwrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *step_lexerin , *step_lexerout ;

typedef int yy_state_type;

extern int step_lexerlineno;

int step_lexerlineno = 1;

extern char *step_lexertext;
#define yytext_ptr step_lexertext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up step_lexertext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	step_lexerleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 44
#define YY_END_OF_BUFFER 45
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[185] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   45,    1,    1,   43,    1,    1,
       43,   42,    2,   42,    4,    5,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   21,   23,
       22,   26,   43,   28,   43,   43,   43,   43,   33,   35,
       34,   36,   37,   39,   38,   41,   40,    0,    0,    0,
        2,    5,    5,    0,    0,    0,    7,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   36,   41,   40,    3,    0,
        0,    0,    0,   12,    0,    7,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   24,   25,    0,    0,   29,
        0,   27,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   16,    0,    0,    8,   13,
        0,    0,    0,    0,   14,    9,    0,   31,   32,   30,
       10,   20,    0,    0,   15,    0,    0,    0,    0,    6,
        0,   18,    0,    0,   19,    0,    0,    0,    0,    0,
       17,    0,   11,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    9,    1,    1,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,    1,
        1,    1,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   22,   23,   24,   25,   26,   27,
       22,   28,   29,   30,   31,   32,   33,   34,   35,   22,
        1,    1,    1,    1,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   22,   22,   46,   47,   48,
       49,   50,   22,   51,   52,   53,   54,   55,   56,   57,
       58,   22,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[193] =
    {   0,
        0,    2,    4,    6,   54,    0,  110,    0,  161,    0,
      209,  221,  233,  269,  184,  484,  484,  484,    0,    0,
      140,  138,  484,  484,  484,    0,  122,    0,    0,    1,
        0,  110,    1,    3,  116,    0,    0,    2,  484,  484,
      484,  484,  133,  484,   84,    0,  106,  139,  484,  484,
      484,    0,  484,  484,  484,  119,    0,  144,  104,  113,
      484,    0,    0,  144,  147,  105,  484,    0,  147,  148,
      148,  146,  152,  162,  242,  239,  247,  237,  235,  230,
      240,  252,  243,  268,    0,    0,    0,    0,  484,  265,
      265,  259,  282,  484,  268,  484,  268,  286,  287,  270,

      272,  287,  278,  288,  291,  484,  484,  282,  285,  484,
      288,  484,  293,  297,  291,  297,  313,  315,  316,  324,
      325,  325,  326,  323,  331,  326,  321,  324,  335,  330,
      333,  330,  330,  329,  340,  336,  340,  342,  337,  358,
      367,  368,  368,  366,  362,  484,  361,  364,  484,  484,
      371,  377,  374,  374,  484,  484,  371,  484,  484,  484,
      484,  484,  379,  379,  484,  377,  387,  378,  378,  484,
      391,  484,  396,  409,  484,  395,  400,  410,  414,  404,
      484,  415,  484,  484,  457,  461,  465,  469,  473,  477,
      479,    6

    } ;

static yyconst flex_int16_t yy_def[193] =
    {   0,
      185,  185,  186,  186,  184,    5,    5,    7,    7,    9,
      187,  187,  188,  188,  184,  184,  184,  184,  184,  184,
      189,  189,  184,  184,  184,  190,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  191,  184,  184,  184,  184,  192,  184,  184,  189,
      184,  190,  190,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  191,  184,  192,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,

      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,    0,  184,  184,  184,  184,  184,  184,
      184,  184

    } ;

static yyconst flex_int16_t yy_nxt[543] =
    {   0,
      184,   17,   18,   17,   18,   22,   23,   22,   23,   88,
       87,  184,   64,   71,   76,   94,   75,   66,   83,   77,
       78,   79,  184,   58,   68,   65,   67,   19,   72,   59,
       20,  184,  184,  184,  184,  111,   64,   71,   76,   94,
       75,   66,   83,   77,   78,   79,   58,   68,   65,   67,
       19,   72,   59,   20,   18,   24,   25,   26,   18,   18,
       18,   18,   18,   27,   18,   18,   18,   28,   29,   30,
       31,   32,   18,   18,   18,   18,   18,   33,   34,   18,
       35,   36,   37,   38,   18,   18,   18,   18,   18,   18,
       18,   28,   29,   30,   31,   32,   18,   18,   18,   18,

       33,   34,   18,   35,   36,   37,   38,   18,   18,   18,
       18,   18,   18,   18,   39,   61,   40,   41,   82,   18,
       90,   42,   93,   18,   18,   18,   18,   18,   73,   87,
       69,   63,   84,   43,   18,   70,   18,   18,   18,   18,
       61,   82,   61,   74,   90,   80,   93,   18,   18,   18,
       18,   18,   73,   81,   69,   84,   43,   18,   70,   18,
       18,   18,   18,   44,   85,   18,   74,   18,   18,   80,
       89,   91,   18,   92,   95,   96,   97,   81,   98,   99,
       45,   46,  100,  184,   47,   48,  184,   85,  184,  184,
      184,  184,  184,   89,   91,  184,   92,   95,   96,   97,

      184,   98,   99,  184,   45,   46,  100,   47,   48,   18,
       24,   18,   18,   49,   50,   18,   18,   51,   18,   18,
       18,   18,   24,   18,   18,   49,   50,   18,   18,   51,
       18,   18,   18,   18,   24,   18,   18,   53,   54,   18,
       18,   55,   18,   56,   18,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  101,  102,  103,
      184,  104,  105,  106,  107,  108,  184,  109,   18,   18,
       24,   18,   18,   53,   54,   18,   18,   55,   18,   56,
       18,  101,  102,  103,  104,  105,  106,  107,  110,  108,
      109,  112,  113,  114,  115,  184,  116,  117,  118,  119,

      184,  120,  121,  122,   18,  123,  124,  125,  184,  126,
      127,  128,  110,  129,  112,  113,  114,  130,  115,  116,
      117,  131,  118,  119,  120,  121,  132,  122,  123,  133,
      124,  125,  126,  127,  128,  134,  136,  129,  135,  137,
      138,  130,  139,  141,  131,  140,  142,  184,  143,  132,
      144,  145,  155,  133,  146,  147,  148,  149,  150,  134,
      136,  135,  151,  137,  138,  152,  139,  141,  140,  153,
      142,  143,  154,  144,  156,  145,  155,  146,  147,  148,
      149,  150,  157,  158,  159,  151,  160,  164,  152,  161,
      162,  163,  153,  165,  166,  154,  167,  168,  156,  169,

      184,  170,  171,  172,  184,  173,  157,  158,  159,  174,
      160,  164,  161,  162,  163,  175,  176,  165,  166,  167,
      168,  177,  180,  169,  170,  171,  178,  172,  173,  179,
      181,  183,  174,  182,  184,  184,  184,  184,  175,  184,
      176,  184,  184,  184,  184,  177,  180,  184,  184,  178,
      184,  184,  179,  184,  181,  183,  182,   16,   16,   16,
       16,   21,   21,   21,   21,   52,   52,   52,   52,   57,
       57,   57,   57,   60,   60,   60,   60,   62,  184,   62,
       62,   86,   86,   15,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,

      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184
    } ;

static yyconst flex_int16_t yy_chk[543] =
    {   0,
        0,    1,    1,    2,    2,    3,    3,    4,    4,  192,
       87,    0,   28,   33,   37,   68,   36,   30,   46,   37,
       37,   38,    0,   19,   31,   29,   30,    2,   34,   20,
        2,    0,    0,    0,    0,   85,   28,   33,   37,   68,
       36,   30,   46,   37,   37,   38,   19,   31,   29,   30,
        2,   34,   20,    2,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    7,    7,    7,   60,    7,    7,   45,    7,
       59,    7,   66,    7,    7,    7,    7,    7,   35,   56,
       32,   27,   47,    7,    7,   32,    7,    7,    7,    7,
       22,   45,   21,   35,   59,   43,   66,    7,    7,    7,
        7,    7,   35,   43,   32,   47,    7,    7,   32,    7,
        7,    7,    7,    9,   48,    9,   35,    9,    9,   43,
       58,   64,    9,   65,   69,   70,   71,   43,   72,   73,
        9,    9,   74,   15,    9,    9,    0,   48,    0,    0,
        0,    0,    0,   58,   64,    0,   65,   69,   70,   71,

        0,   72,   73,    0,    9,    9,   74,    9,    9,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   75,   76,   77,
        0,   78,   79,   80,   81,   82,    0,   83,   13,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   75,   76,   77,   78,   79,   80,   81,   84,   82,
       83,   90,   91,   92,   93,    0,   95,   97,   98,   99,

        0,  100,  101,  102,   14,  103,  104,  105,    0,  108,
      109,  111,   84,  113,   90,   91,   92,  114,   93,   95,
       97,  115,   98,   99,  100,  101,  116,  102,  103,  117,
      104,  105,  108,  109,  111,  118,  120,  113,  119,  121,
      122,  114,  123,  125,  115,  124,  126,    0,  127,  116,
      128,  129,  139,  117,  130,  131,  132,  133,  134,  118,
      120,  119,  135,  121,  122,  136,  123,  125,  124,  137,
      126,  127,  138,  128,  140,  129,  139,  130,  131,  132,
      133,  134,  141,  142,  143,  135,  144,  151,  136,  145,
      147,  148,  137,  152,  153,  138,  154,  157,  140,  163,

        0,  164,  166,  167,    0,  168,  141,  142,  143,  169,
      144,  151,  145,  147,  148,  171,  173,  152,  153,  154,
      157,  174,  178,  163,  164,  166,  176,  167,  168,  177,
      179,  182,  169,  180,    0,    0,    0,    0,  171,    0,
      173,    0,    0,    0,    0,  174,  178,    0,    0,  176,
        0,    0,  177,    0,  179,  182,  180,  185,  185,  185,
      185,  186,  186,  186,  186,  187,  187,  187,  187,  188,
      188,  188,  188,  189,  189,  189,  189,  190,    0,  190,
      190,  191,  191,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,

      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int step_lexer_flex_debug;
int step_lexer_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *step_lexertext;
#line 1 "step_lexer.l"
#line 2 "step_lexer.l"
#ifdef HAVE_CONFIG_H
    #include "pips_config.h"
#endif

#include "defines-local.h"
#include "step_bison_parser.h"
#define YY_NO_INPUT 1





#line 673 "<stdout>"

#define INITIAL 0
#define unknow_pragma 1
#define omp_pragma 2
#define omp_reduction 3
#define step_pragma 4
#define variable_list 5
#define schedule_arg 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int step_lexerlex_destroy (void );

int step_lexerget_debug (void );

void step_lexerset_debug (int debug_flag  );

YY_EXTRA_TYPE step_lexerget_extra (void );

void step_lexerset_extra (YY_EXTRA_TYPE user_defined  );

FILE *step_lexerget_in (void );

void step_lexerset_in  (FILE * in_str  );

FILE *step_lexerget_out (void );

void step_lexerset_out  (FILE * out_str  );

yy_size_t step_lexerget_leng (void );

char *step_lexerget_text (void );

int step_lexerget_lineno (void );

void step_lexerset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int step_lexerwrap (void );
#else
extern int step_lexerwrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( step_lexertext, step_lexerleng, 1, step_lexerout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( step_lexerin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( step_lexerin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, step_lexerin))==0 && ferror(step_lexerin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(step_lexerin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int step_lexerlex (void);

#define YY_DECL int step_lexerlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after step_lexertext and step_lexerleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( step_lexerleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(step_lexertext[step_lexerleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 26 "step_lexer.l"

#line 872 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! step_lexerin )
			step_lexerin = stdin;

		if ( ! step_lexerout )
			step_lexerout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			step_lexerensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				step_lexer_create_buffer(step_lexerin,YY_BUF_SIZE );
		}

		step_lexer_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of step_lexertext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 185 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 484 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "step_lexer.l"
{yy_push_state(unknow_pragma); yymore();}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 28 "step_lexer.l"
{yy_pop_state(); step_lexerlval.string = strdup(step_lexertext); return TK_RAW;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "step_lexer.l"
{yy_push_state(omp_pragma); return TK_OMP_PRAGMA;}
	YY_BREAK

case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 33 "step_lexer.l"
{yy_pop_state(); return TK_EOL;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 34 "step_lexer.l"
{step_lexerlval.string = strdup(step_lexertext); return TK_COMMENT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 35 "step_lexer.l"
{step_lexerlval.integer = STEP_PARALLEL; return TK_OMP_PARALLEL;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 36 "step_lexer.l"
{step_lexerlval.integer = STEP_DO; return TK_OMP_LOOP;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 37 "step_lexer.l"
{step_lexerlval.integer = STEP_MASTER; return TK_OMP_MASTER;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 38 "step_lexer.l"
{step_lexerlval.integer = STEP_SINGLE; return TK_OMP_SINGLE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 39 "step_lexer.l"
{step_lexerlval.integer = STEP_BARRIER; return TK_OMP_BARRIER;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 40 "step_lexer.l"
{/*is stored as both a directive and a clause */
    step_lexerlval.integer = STEP_THREADPRIVATE; yy_push_state(variable_list); return TK_OMP_THREADPRIVATE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "step_lexer.l"
{step_lexerlval.integer = 0; return TK_OMP_END;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "step_lexer.l"
{return TK_OMP_NOWAIT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "step_lexer.l"
{yy_push_state(variable_list); return TK_OMP_SHARED;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 "step_lexer.l"
{yy_push_state(variable_list); return TK_OMP_PRIVATE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "step_lexer.l"
{yy_push_state(variable_list); return TK_OMP_COPYIN;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 49 "step_lexer.l"
{yy_push_state(variable_list); return TK_OMP_FIRSTPRIVATE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 50 "step_lexer.l"
{yy_push_state(schedule_arg); return TK_OMP_SCHEDULE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 51 "step_lexer.l"
{yy_push_state(omp_reduction); return TK_OMP_REDUCTION;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 52 "step_lexer.l"
{yy_push_state(variable_list); return TK_OMP_DEFAULT;}
	YY_BREAK


case 21:
YY_RULE_SETUP
#line 55 "step_lexer.l"
{return TK_LPAREN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "step_lexer.l"
{step_lexerlval.integer = STEP_SUM_REDUCE; return TK_OPERATOR;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "step_lexer.l"
{step_lexerlval.integer = STEP_PROD_REDUCE; return TK_OPERATOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "step_lexer.l"
{step_lexerlval.integer = STEP_MAX_REDUCE; return TK_OPERATOR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 59 "step_lexer.l"
{step_lexerlval.integer = STEP_MIN_REDUCE; return TK_OPERATOR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 60 "step_lexer.l"
{yy_pop_state(); yy_push_state(variable_list); return TK_COLON;}
	YY_BREAK

case 27:
YY_RULE_SETUP
#line 64 "step_lexer.l"
{yy_push_state(step_pragma); return TK_STEP_PRAGMA;}
	YY_BREAK

case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 66 "step_lexer.l"
{yy_pop_state(); return TK_EOL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "step_lexer.l"
{step_lexerlval.integer = STEP_TRANSFORMATION_MPI; return TK_STEP_TRANSFORMATION;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "step_lexer.l"
{step_lexerlval.integer = STEP_TRANSFORMATION_OMP; return TK_STEP_TRANSFORMATION;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "step_lexer.l"
{step_lexerlval.integer = STEP_TRANSFORMATION_HYBRID; return TK_STEP_TRANSFORMATION;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "step_lexer.l"
{step_lexerlval.integer = STEP_TRANSFORMATION_SEQ; return TK_STEP_TRANSFORMATION;}
	YY_BREAK


case 33:
YY_RULE_SETUP
#line 75 "step_lexer.l"
{return TK_LPAREN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "step_lexer.l"
{return TK_COMMA;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "step_lexer.l"
{yy_pop_state(); return TK_RPAREN;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "step_lexer.l"
{step_lexerlval.string = strdup(step_lexertext); return TK_IDENT;}
	YY_BREAK


case 37:
YY_RULE_SETUP
#line 82 "step_lexer.l"
{return TK_LPAREN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "step_lexer.l"
{return TK_COMMA;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "step_lexer.l"
{yy_pop_state(); return TK_RPAREN;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 85 "step_lexer.l"
{step_lexerlval.string = strdup(step_lexertext); return TK_IDENT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 86 "step_lexer.l"
{step_lexerlval.string = strdup(step_lexertext); return TK_IDENT;}
	YY_BREAK

case 42:
YY_RULE_SETUP
#line 89 "step_lexer.l"
{}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 90 "step_lexer.l"
{pips_debug(1, "\tunexepected character: %s\n", step_lexertext); return TK_ERROR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 92 "step_lexer.l"
ECHO;
	YY_BREAK
#line 1197 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(unknow_pragma):
case YY_STATE_EOF(omp_pragma):
case YY_STATE_EOF(omp_reduction):
case YY_STATE_EOF(step_pragma):
case YY_STATE_EOF(variable_list):
case YY_STATE_EOF(schedule_arg):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed step_lexerin at a new source and called
			 * step_lexerlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = step_lexerin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( step_lexerwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * step_lexertext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of step_lexerlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					step_lexerrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ((int)  number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			step_lexerrestart(step_lexerin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > (yy_size_t)YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) step_lexerrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 185 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 185 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 184);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					step_lexerrestart(step_lexerin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( step_lexerwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve step_lexertext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void step_lexerrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        step_lexerensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            step_lexer_create_buffer(step_lexerin,YY_BUF_SIZE );
	}

	step_lexer_init_buffer(YY_CURRENT_BUFFER,input_file );
	step_lexer_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void step_lexer_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		step_lexerpop_buffer_state();
	 *		step_lexerpush_buffer_state(new_buffer);
     */
	step_lexerensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	step_lexer_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (step_lexerwrap()) processing, but the only time this flag
	 * is looked at is after step_lexerwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void step_lexer_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	step_lexerin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE step_lexer_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) step_lexeralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in step_lexer_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) step_lexeralloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in step_lexer_create_buffer()" );

	b->yy_is_our_buffer = 1;

	step_lexer_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with step_lexer_create_buffer()
 * 
 */
    void step_lexer_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		step_lexerfree((void *) b->yy_ch_buf  );

	step_lexerfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a step_lexerrestart() or at EOF.
 */
    static void step_lexer_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	step_lexer_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then step_lexer_init_buffer was _probably_
     * called from step_lexerrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void step_lexer_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		step_lexer_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void step_lexerpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	step_lexerensure_buffer_stack();

	/* This block is copied from step_lexer_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from step_lexer_switch_to_buffer. */
	step_lexer_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void step_lexerpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	step_lexer_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		step_lexer_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void step_lexerensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)step_lexeralloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in step_lexerensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)step_lexerrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in step_lexerensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE step_lexer_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) step_lexeralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in step_lexer_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	step_lexer_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to step_lexerlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       step_lexer_scan_bytes() instead.
 */
YY_BUFFER_STATE step_lexer_scan_string (yyconst char * yystr )
{
    
	return step_lexer_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to step_lexerlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE step_lexer_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) step_lexeralloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in step_lexer_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = step_lexer_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in step_lexer_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) step_lexeralloc(new_size  );

		else
			(yy_start_stack) = (int *) step_lexerrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up step_lexertext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		step_lexertext[step_lexerleng] = (yy_hold_char); \
		(yy_c_buf_p) = step_lexertext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		step_lexerleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int step_lexerget_lineno  (void)
{
        
    return step_lexerlineno;
}

/** Get the input stream.
 * 
 */
FILE *step_lexerget_in  (void)
{
        return step_lexerin;
}

/** Get the output stream.
 * 
 */
FILE *step_lexerget_out  (void)
{
        return step_lexerout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t step_lexerget_leng  (void)
{
        return step_lexerleng;
}

/** Get the current token.
 * 
 */

char *step_lexerget_text  (void)
{
        return step_lexertext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void step_lexerset_lineno (int  line_number )
{
    
    step_lexerlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see step_lexer_switch_to_buffer
 */
void step_lexerset_in (FILE *  in_str )
{
        step_lexerin = in_str ;
}

void step_lexerset_out (FILE *  out_str )
{
        step_lexerout = out_str ;
}

int step_lexerget_debug  (void)
{
        return step_lexer_flex_debug;
}

void step_lexerset_debug (int  bdebug )
{
        step_lexer_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from step_lexerlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    step_lexerin = stdin;
    step_lexerout = stdout;
#else
    step_lexerin = (FILE *) 0;
    step_lexerout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * step_lexerlex_init()
     */
    return 0;
}

/* step_lexerlex_destroy is for both reentrant and non-reentrant scanners. */
int step_lexerlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		step_lexer_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		step_lexerpop_buffer_state();
	}

	/* Destroy the stack itself. */
	step_lexerfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        step_lexerfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * step_lexerlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *step_lexeralloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *step_lexerrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void step_lexerfree (void * ptr )
{
	free( (char *) ptr );	/* see step_lexerrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 92 "step_lexer.l"




