/*
Runtime API handler (generated from step_api.h )
*/
{RT_STEP_alltoall_full_interlaced, { words_call_intrinsic, 0} },
{RT_STEP_alltoall_full, { words_call_intrinsic, 0} },
{RT_STEP_alltoall_partial_interlaced, { words_call_intrinsic, 0} },
{RT_STEP_alltoall_partial, { words_call_intrinsic, 0} },
{RT_STEP_alltoall, { words_call_intrinsic, 0} },
{RT_STEP_barrier, { words_call_intrinsic, 0} },
{RT_STEP_compute_loopslices, { words_call_intrinsic, 0} },
{RT_STEP_construct_begin, { words_call_intrinsic, 0} },
{RT_STEP_construct_end, { words_call_intrinsic, 0} },
{RT_STEP_finalize, { words_call_intrinsic, 0} },
{RT_STEP_flush, { words_call_intrinsic, 0} },
{RT_STEP_get_commsize, { words_call_intrinsic, 0} },
{RT_STEP_get_loopbounds, { words_call_intrinsic, 0} },
{RT_STEP_get_rank, { words_call_intrinsic, 0} },
{RT_STEP_init_arrayregions, { words_call_intrinsic, 0} },
{RT_STEP_init_c_order, { words_call_intrinsic, 0} },
{RT_STEP_init_fortran_order, { words_call_intrinsic, 0} },
{RT_STEP_initreduction, { words_call_intrinsic, 0} },
{RT_STEP_reduction, { words_call_intrinsic, 0} },
{RT_STEP_register_alltoall_partial, { words_call_intrinsic, 0} },
{RT_STEP_set_interlaced_sendregions, { words_call_intrinsic, 0} },
{RT_STEP_set_recvregions, { words_call_intrinsic, 0} },
{RT_STEP_set_reduction_sendregions, { words_call_intrinsic, 0} },
{RT_STEP_set_sendregions, { words_call_intrinsic, 0} },
{RT_STEP_timer_dump, { words_call_intrinsic, 0} },
{RT_STEP_timer_event, { words_call_intrinsic, 0} },
{RT_STEP_timer_finalize, { words_call_intrinsic, 0} },
{RT_STEP_timer_init, { words_call_intrinsic, 0} },
{RT_STEP_timer_reset, { words_call_intrinsic, 0} },
/* Runtime API handler (end) */
