/* Make sure the declaration list is correct when a dummy structs are
 * used.
 *
 * Second half of dummy03.c, shortened. The anonymous struct used to
 * declare type foo must belong to the declaration list generated by
 * the C parser.
 */

struct {
  int e;
} foo(void);
