!\n!   Genereted file from step_common.h\n!

       INTEGER STEP_MAX_NB_LOOPSLICES
       PARAMETER (STEP_MAX_NB_LOOPSLICES = 16)

       INTEGER STEP_INDEX_SLICE_LOW
       PARAMETER (STEP_INDEX_SLICE_LOW = 1)

       INTEGER STEP_INDEX_SLICE_UP
       PARAMETER (STEP_INDEX_SLICE_UP = 2)

       INTEGER STEP_C
       PARAMETER (STEP_C = 0)

       INTEGER STEP_FORTRAN
       PARAMETER (STEP_FORTRAN = 1)

       INTEGER STEP_PARALLEL
       PARAMETER (STEP_PARALLEL = 100)

       INTEGER STEP_DO
       PARAMETER (STEP_DO = 101)

       INTEGER STEP_PARALLEL_DO
       PARAMETER (STEP_PARALLEL_DO = 102)

       INTEGER STEP_MASTER
       PARAMETER (STEP_MASTER = 103)

       INTEGER STEP_SINGLE
       PARAMETER (STEP_SINGLE = 106)

       INTEGER STEP_THREADPRIVATE
       PARAMETER (STEP_THREADPRIVATE = 107)

       INTEGER STEP_NOWAIT
       PARAMETER (STEP_NOWAIT = 0)

       INTEGER STEP_WAIT
       PARAMETER (STEP_WAIT = 1)

       INTEGER STEP_INTEGER
       PARAMETER (STEP_INTEGER = 0)

       INTEGER STEP_REAL
       PARAMETER (STEP_REAL = 1)

       INTEGER STEP_DOUBLE_PRECISION
       PARAMETER (STEP_DOUBLE_PRECISION = 2)

       INTEGER STEP_COMPLEX
       PARAMETER (STEP_COMPLEX = 3)

       INTEGER STEP_INTEGER1
       PARAMETER (STEP_INTEGER1 = 4)

       INTEGER STEP_INTEGER2
       PARAMETER (STEP_INTEGER2 = 5)

       INTEGER STEP_INTEGER4
       PARAMETER (STEP_INTEGER4 = 6)

       INTEGER STEP_INTEGER8
       PARAMETER (STEP_INTEGER8 = 7)

       INTEGER STEP_REAL4
       PARAMETER (STEP_REAL4 = 8)

       INTEGER STEP_REAL8
       PARAMETER (STEP_REAL8 = 9)

       INTEGER STEP_REAL16
       PARAMETER (STEP_REAL16 = 10)

       INTEGER STEP_COMPLEX8
       PARAMETER (STEP_COMPLEX8 = 11)

       INTEGER STEP_COMPLEX16
       PARAMETER (STEP_COMPLEX16 = 12)

       INTEGER STEP_TYPE_UNDEFINED
       PARAMETER (STEP_TYPE_UNDEFINED = 13)

       INTEGER STEP_TAG_DEFAULT
       PARAMETER (STEP_TAG_DEFAULT = 0)

       INTEGER STEP_NBLOCKING_ALG
       PARAMETER (STEP_NBLOCKING_ALG = 0)

       INTEGER STEP_PROD_REDUCE
       PARAMETER (STEP_PROD_REDUCE = 0)

       INTEGER STEP_MAX_REDUCE
       PARAMETER (STEP_MAX_REDUCE = 1)

       INTEGER STEP_MIN_REDUCE
       PARAMETER (STEP_MIN_REDUCE = 2)

       INTEGER STEP_SUM_REDUCE
       PARAMETER (STEP_SUM_REDUCE = 3)

       INTEGER STEP_UNDEF_REDUCE
       PARAMETER (STEP_UNDEF_REDUCE = 4)
