# $Id: Makefile 6643 2015-12-09 18:02:11Z coelho $

PARALLEL_VALIDATION = 1
include ../validate.mk

clean: local-clean
local-clean:
	$(RM) -r .w0.tmp .loop_tiling.tmp .exception.tmp .effects.tmp \
	PYPS[-_a-zA-Z0-9][-_a-zA-Z0-9][-_a-zA-Z0-9][-_a-zA-Z0-9][-_a-zA-Z0-9][-_a-zA-Z0-9]
