# EFFECTS
DBR_PROPER_REFERENCES: STATEMENT_FUNCTION_METHODS
DBR_CUMULATED_REFERENCES: STATEMENT_FUNCTION_METHODS
DBR_PROPER_POINTER_EFFECTS: 	STATEMENT_FUNCTION_METHODS
DBR_CUMULATED_POINTER_EFFECTS:	STATEMENT_FUNCTION_METHODS
DBR_SUMMARY_POINTER_EFFECTS: 	NEWGEN_METHODS
DBR_PROPER_EFFECTS: 		STATEMENT_FUNCTION_METHODS
DBR_CUMULATED_EFFECTS: 	STATEMENT_FUNCTION_METHODS
DBR_SUMMARY_EFFECTS: 		NEWGEN_METHODS
DBR_IN_EFFECTS: 		STATEMENT_FUNCTION_METHODS
DBR_CUMULATED_IN_EFFECTS: 	STATEMENT_FUNCTION_METHODS
DBR_OUT_EFFECTS: 		STATEMENT_FUNCTION_METHODS
DBR_IN_SUMMARY_EFFECTS: 	NEWGEN_METHODS
DBR_OUT_SUMMARY_EFFECTS: 	NEWGEN_METHODS

# LIVE PATHS
DBR_LIVE_IN_PATHS: 	STATEMENT_FUNCTION_METHODS
DBR_LIVE_OUT_PATHS: 	STATEMENT_FUNCTION_METHODS
DBR_LIVE_IN_SUMMARY_PATHS: 	NEWGEN_METHODS
DBR_LIVE_OUT_SUMMARY_PATHS: 	NEWGEN_METHODS


# REDUCTIONS
DBR_PROPER_REDUCTIONS: 	STATEMENT_FUNCTION_METHODS
DBR_CUMULATED_REDUCTIONS: 	STATEMENT_FUNCTION_METHODS
DBR_SUMMARY_REDUCTIONS: 	NEWGEN_METHODS
DBR_REDUCTION_PARALLEL_LOOPS: 	NEWGEN_METHODS

DBR_STATIC_CONTROL: STATIC_STATEMENT_MAPPING_METHODS

# PAF stuff...
#DBR_ADFG: 			DONOTHING_METHODS
#DBR_ADFG_FILE: 		STRING_METHODS
#DBR_BDT: 			DONOTHING_METHODS
#DBR_BDT_FILE: 			STRING_METHODS
#DBR_PLC: 			DONOTHING_METHODS
#DBR_PLC_FILE: 			STRING_METHODS

# REGIONS
DBR_REGIONS: 			STATEMENT_FUNCTION_METHODS
DBR_INV_REGIONS: 		STATEMENT_FUNCTION_METHODS
DBR_PROPER_REGIONS: 		STATEMENT_FUNCTION_METHODS
DBR_SUMMARY_REGIONS: 		NEWGEN_METHODS
DBR_POINTER_REGIONS: 		STATEMENT_FUNCTION_METHODS
DBR_INV_POINTER_REGIONS: 	STATEMENT_FUNCTION_METHODS
DBR_PROPER_POINTER_REGIONS: 	STATEMENT_FUNCTION_METHODS
DBR_SUMMARY_POINTER_REGIONS: 	NEWGEN_METHODS
DBR_IN_REGIONS: 		STATEMENT_FUNCTION_METHODS
DBR_INV_IN_REGIONS: 		STATEMENT_FUNCTION_METHODS
DBR_CUMULATED_IN_REGIONS: 	STATEMENT_FUNCTION_METHODS
DBR_IN_SUMMARY_REGIONS: 	NEWGEN_METHODS
DBR_OUT_REGIONS: 		STATEMENT_FUNCTION_METHODS
DBR_OUT_SUMMARY_REGIONS: 	NEWGEN_METHODS
DBR_PRIVATIZED_REGIONS: 	STATEMENT_FUNCTION_METHODS
DBR_COPY_OUT_REGIONS:     STATEMENT_FUNCTION_METHODS

# DBR_USEFUL_VARIABLES_EFFECTS:     NEWGEN_METHODS
DBR_USEFUL_VARIABLES_REGIONS:     NEWGEN_METHODS
DBR_USEFUL_VARIABLES_POINTER_REGIONS:     NEWGEN_METHODS

DBR_ALIAS_CLASSES: 		NEWGEN_METHODS
DBR_ALIAS_LISTS: 		NEWGEN_METHODS
DBR_IN_ALIAS_PAIRS: 		NEWGEN_METHODS
DBR_OUT_ALIAS_PAIRS: 		NEWGEN_METHODS

DBR_COMPSEC: 			STATEMENT_MAPPING_METHODS
DBR_SUMMARY_COMPSEC: 		NEWGEN_METHODS

# SEMANTICS
DBR_TRANSFORMERS: 		STATEMENT_MAPPING_METHODS
DBR_PRECONDITIONS: 		STATEMENT_MAPPING_METHODS
DBR_SUMMARY_TRANSFORMER: 	NEWGENNOCHECK_METHODS
DBR_SUMMARY_PRECONDITION: 	NEWGENNOCHECK_METHODS
DBR_INITIAL_PRECONDITION: 	NEWGENNOCHECK_METHODS
DBR_PROGRAM_PRECONDITION: 	NEWGENNOCHECK_METHODS

DBR_MUST_CONTINUATION: 	STATEMENT_MAPPING_METHODS
DBR_MAY_CONTINUATION: 		STATEMENT_MAPPING_METHODS
DBR_MUST_SUMMARY_CONTINUATION: NEWGENNOCHECK_METHODS
DBR_MAY_SUMMARY_CONTINUATION: NEWGENNOCHECK_METHODS

# Resource for alias analysis
DBR_ALIAS_ASSOCIATIONS: NEWGEN_METHODS

# Resource for points-to analysis
DBR_POINTS_TO: STATEMENT_FUNCTION_METHODS
DBR_POINTS_TO_OUT: 		NEWGEN_METHODS
DBR_POINTS_TO_IN: 		NEWGEN_METHODS
DBR_INITIAL_POINTS_TO: 	NEWGEN_METHODS
DBR_PROGRAM_POINTS_TO: 	NEWGEN_METHODS
DBR_INIT_POINTS_TO_LIST: NEWGEN_METHODS


# Resource for simple pointer values analyses
DBR_SIMPLE_POINTER_VALUES: STATEMENT_FUNCTION_METHODS
DBR_IN_SIMPLE_POINTER_VALUES: NEWGEN_METHODS
DBR_OUT_SIMPLE_POINTER_VALUES: NEWGEN_METHODS
DBR_INITIAL_SIMPLE_POINTER_VALUES: NEWGEN_METHODS
DBR_PROGRAM_SIMPLE_POINTER_VALUES: NEWGEN_METHODS


# Resource for used before set analysis
DBR_UBS: 			NEWGEN_METHODS

# complexity
DBR_COMPLEXITIES: 		STATEMENT_MAPPING_METHODS
DBR_SUMMARY_COMPLEXITY: 	NEWGEN_METHODS

# FILE NAMES
DBR_USER_FILE: 		STRING_METHODS
DBR_INITIAL_FILE: 		STRING_METHODS
DBR_SOURCE_FILE: 		STRING_METHODS
DBR_C_SOURCE_FILE: 		STRING_METHODS
DBR_PARSED_PRINTED_FILE: 	STRING_METHODS
DBR_PRINTED_FILE: 		STRING_METHODS
DBR_GRAPH_PRINTED_FILE: 	STRING_METHODS
DBR_FLINTED_FILE: 		STRING_METHODS
DBR_PARALLELPRINTED_FILE: 	STRING_METHODS
DBR_CALLGRAPH_FILE: 		STRING_METHODS
DBR_WP65_BANK_FILE: 		STRING_METHODS
DBR_WP65_COMPUTE_FILE: 	STRING_METHODS
DBR_ICFG_FILE: 		STRING_METHODS
DBR_DVICFG_FILE: 		STRING_METHODS
DBR_DG_FILE: 			STRING_METHODS
DBR_DVDG_FILE: 		STRING_METHODS
DBR_DOTDG_FILE: 		STRING_METHODS
DBR_ALIAS_FILE: 		STRING_METHODS
DBR_DVCG_FILE: 		STRING_METHODS
DBR_STATS_FILE: 		STRING_METHODS
DBR_SYMBOL_TABLE_FILE: 	STRING_METHODS
DBR_PARSED_SYMBOL_TABLE_FILE: 	STRING_METHODS
DBR_XML_PRINTED_FILE: 		STRING_METHODS
DBR_SPOC_FILE: STRING_METHODS
DBR_TERAPIX_FILE: STRING_METHODS
DBR_OPENCL_FILE: STRING_METHODS
DBR_SIGMAC_FILE: STRING_METHODS
DBR_LOOPS_FILE: STRING_METHODS
DBR_HTML_IR_FILE: STRING_METHODS
DBR_GPU_XML_FILE: STRING_METHODS
DBR_PATH_TRANSFORMER_FILE: STRING_METHODS


# STEP FILES
# Default : NEWGEN_METHOD
# For files : STRING_METHODS
# for all types like "statement ->" : STATEMENT_FUNCTION_METHODS
# unserializable : GENFREE_METHODS
DBR_STEP_DIRECTIVES: GENFREE_METHODS
DBR_STEP_COMM: GENFREE_METHODS
DBR_STEP_SEND_REGIONS: STATEMENT_FUNCTION_METHODS
DBR_STEP_RECV_REGIONS: STATEMENT_FUNCTION_METHODS
DBR_STEP_FILE: STRING_METHODS

# HPFC GENERATED FILES
DBR_HPFC_FILTERED_FILE: 	STRING_METHODS
DBR_HPFC_PARAMETERS: 		STRING_METHODS
DBR_HPFC_HOST: 		STRING_METHODS
DBR_HPFC_NODE: 		STRING_METHODS
DBR_HPFC_RTINIT: 		STRING_METHODS
DBR_HPFC_COMMONS: 		DONOTHING_METHODS
DBR_HPFC_INSTALLATION: 	DONOTHING_METHODS

# LOST
DBR_CHAINS: 			GENFREE_METHODS
DBR_DG: 			GENFREE_METHODS
DBR_LOOPS: 			NEWGEN_METHODS
DBR_SDG: 			GENFREE_METHODS

# CODE...
DBR_PARSED_CODE: 		NEWGEN_METHODS
DBR_PARALLELIZED_CODE: 		NEWGEN_METHODS
DBR_SHARED_SPIRE_CODE: 		NEWGEN_METHODS
DBR_DISTRIBUTED_SPIRE_CODE: 	NEWGEN_METHODS

# Schedule using HBDSC
DBR_SCHEDULE: NEWGEN_METHODS

# dummy resource for the moment
DBR_PRIVATIZED: 	DONOTHING_METHODS
# DBR_SCOP_PRINTED: 	NEWGEN_METHODS
# DBR_SCOP_OUTLINED: 	NEWGEN_METHODS
# DBR_REINDEXED_CODE: 	NEWGEN_METHODS
DBR_CALLEES: 			NEWGEN_METHODS
DBR_CALLERS: 			NEWGEN_METHODS
DBR_CODE: 			NEWGEN_METHODS
DBR_HEIGHT: 			STRING_METHODS
DBR_DEPTH: 			STRING_METHODS

# DECLARATIONS is a special resource to impose that each compilation unit
# must be parsed before its functions. It is in fact a hash table
# containing C keywords and a compilation unit typedef names.

DBR_DECLARATIONS: 		DECLARATIONS_METHODS

# Name of the user input file used to generate a module or a
# compilation unit The file is located outside of the workspace and
# may change or even disappear while PIPS is running

DBR_INPUT_FILE_NAME: 		STRING_METHODS

# Misc files.
DBR_CROUGH: 			STRING_METHODS
DBR_C_PRINTED_FILE: 		STRING_METHODS
DBR_NEW_DECLARATIONS: 		STRING_METHODS

# The resource DBR_NEW_DECLARATIONS is used by top_down_array_resizing

DBR_SMALLTALK_CODE_FILE: STRING_METHODS
# used for PRINT_CODE_SMALLTALK pass

# PROGRAM resources
#
# entities are tabulated... here are some wrappers that expect
# entity_domain as the pointer value... see bootstrap/bootstrap.c
#
DBR_HPFC_STATUS: 		NEWGEN_METHODS
DBR_ENTITIES: 			ENTITY_METHODS
DBR_KERNELS: NEWGEN_METHODS
DBR_SIMD_TREEMATCH: NEWGEN_METHODS
DBR_SIMD_OPERATOR_MAPPINGS: NEWGEN_METHODS

# Kernels
DBR_KERNEL_COPY_IN: NEWGEN_METHODS
DBR_KERNEL_COPY_OUT: NEWGEN_METHODS

# SCALOPES
DBR_SESAM_BUFFERS_FILE: STRING_METHODS
