#ifndef _newgen_abc_private_included
#define _newgen_abc_private_included
#define _gen_abc_private_start 171
/*
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY NEWGEN.
 *
 * PLEASE DO NOT MODIFY IT.
 */

#if !defined(_newgen_entity_domain_defined_)
#define _newgen_entity_domain_defined_
#define ENTITY_NEWGEN_DOMAIN (entity_domain)
#define entity_NEWGEN_DOMAIN (entity_domain)
typedef struct _newgen_struct_entity_ * entity;
#endif /* _newgen_entity_domain_defined_ */

#define abc_checked_domain (_gen_abc_private_start+0)
#if !defined(_newgen_abc_checked_domain_defined_)
#define _newgen_abc_checked_domain_defined_
#define ABC_CHECKED_NEWGEN_DOMAIN (abc_checked_domain)
#define abc_checked_NEWGEN_DOMAIN (abc_checked_domain)
typedef struct _newgen_struct_abc_checked_ * abc_checked;
#endif /* _newgen_abc_checked_domain_defined_ */

#define array_dimension_checked_domain (_gen_abc_private_start+1)
#if !defined(_newgen_array_dimension_checked_domain_defined_)
#define _newgen_array_dimension_checked_domain_defined_
#define ARRAY_DIMENSION_CHECKED_NEWGEN_DOMAIN (array_dimension_checked_domain)
#define array_dimension_checked_NEWGEN_DOMAIN (array_dimension_checked_domain)
typedef struct _newgen_struct_array_dimension_checked_ * array_dimension_checked;
#endif /* _newgen_array_dimension_checked_domain_defined_ */

#define dimension_checked_domain (_gen_abc_private_start+2)
#if !defined(_newgen_dimension_checked_domain_defined_)
#define _newgen_dimension_checked_domain_defined_
#define DIMENSION_CHECKED_NEWGEN_DOMAIN (dimension_checked_domain)
#define dimension_checked_NEWGEN_DOMAIN (dimension_checked_domain)
typedef struct _newgen_struct_dimension_checked_ * dimension_checked;
#endif /* _newgen_dimension_checked_domain_defined_ */

/* ABC_CHECKED
 */
#define ABC_CHECKED(x) ((abc_checked)((x).p))
#define abc_checked_CAST(x) ABC_CHECKED(x)
#define ABC_CHECKED_CAST(x) ABC_CHECKED(x)
#define ABC_CHECKED_(x) ((x).e)
#define ABC_CHECKED_TYPE abc_checked
#define abc_checked_TYPE abc_checked
#define abc_checked_undefined ((abc_checked)gen_chunk_undefined)
#define abc_checked_undefined_p(x) ((x)==abc_checked_undefined)

extern abc_checked copy_abc_checked(abc_checked);
extern void free_abc_checked(abc_checked);
extern abc_checked check_abc_checked(abc_checked);
extern bool abc_checked_consistent_p(abc_checked);
extern bool abc_checked_defined_p(abc_checked);
#define gen_ABC_CHECKED_cons gen_abc_checked_cons
extern list gen_abc_checked_cons(abc_checked, list);
extern void abc_checked_assign_contents(abc_checked, abc_checked);
extern void abc_checked_non_recursive_free(abc_checked);
extern void write_abc_checked(FILE*, abc_checked);
extern abc_checked read_abc_checked(FILE*);
extern abc_checked make_abc_checked(list);

struct _newgen_struct_abc_checked_ {
  intptr_t _type_;
  list _abc_checked_holder_;
};

#define abc_checked_domain_number(x) ((x)->_type_)
#define abc_checked_list(x) ((x)->_abc_checked_holder_)

/* ARRAY_DIMENSION_CHECKED
 */
#define ARRAY_DIMENSION_CHECKED(x) ((array_dimension_checked)((x).p))
#define array_dimension_checked_CAST(x) ARRAY_DIMENSION_CHECKED(x)
#define ARRAY_DIMENSION_CHECKED_CAST(x) ARRAY_DIMENSION_CHECKED(x)
#define ARRAY_DIMENSION_CHECKED_(x) ((x).e)
#define ARRAY_DIMENSION_CHECKED_TYPE array_dimension_checked
#define array_dimension_checked_TYPE array_dimension_checked
#define array_dimension_checked_undefined ((array_dimension_checked)gen_chunk_undefined)
#define array_dimension_checked_undefined_p(x) ((x)==array_dimension_checked_undefined)

extern array_dimension_checked copy_array_dimension_checked(array_dimension_checked);
extern void free_array_dimension_checked(array_dimension_checked);
extern array_dimension_checked check_array_dimension_checked(array_dimension_checked);
extern bool array_dimension_checked_consistent_p(array_dimension_checked);
extern bool array_dimension_checked_defined_p(array_dimension_checked);
#define gen_ARRAY_DIMENSION_CHECKED_cons gen_array_dimension_checked_cons
extern list gen_array_dimension_checked_cons(array_dimension_checked, list);
extern void array_dimension_checked_assign_contents(array_dimension_checked, array_dimension_checked);
extern void array_dimension_checked_non_recursive_free(array_dimension_checked);
extern void write_array_dimension_checked(FILE*, array_dimension_checked);
extern array_dimension_checked read_array_dimension_checked(FILE*);
extern array_dimension_checked make_array_dimension_checked(entity, list);

struct _newgen_struct_array_dimension_checked_ {
  intptr_t _type_;
  entity _array_dimension_checked_array_; /* array:entity */
  list _array_dimension_checked_dims_; /* dims:dimension_checked* */
};

#define array_dimension_checked_domain_number(x) ((x)->_type_)
#define array_dimension_checked_array_(x) array_dimension_checked_array(x) /* old hack compatible */
#define array_dimension_checked_array(x) ((x)->_array_dimension_checked_array_)
#define array_dimension_checked_dims_(x) array_dimension_checked_dims(x) /* old hack compatible */
#define array_dimension_checked_dims(x) ((x)->_array_dimension_checked_dims_)

/* DIMENSION_CHECKED
 */
#define DIMENSION_CHECKED(x) ((dimension_checked)((x).p))
#define dimension_checked_CAST(x) DIMENSION_CHECKED(x)
#define DIMENSION_CHECKED_CAST(x) DIMENSION_CHECKED(x)
#define DIMENSION_CHECKED_(x) ((x).e)
#define DIMENSION_CHECKED_TYPE dimension_checked
#define dimension_checked_TYPE dimension_checked
#define dimension_checked_undefined ((dimension_checked)gen_chunk_undefined)
#define dimension_checked_undefined_p(x) ((x)==dimension_checked_undefined)

extern dimension_checked copy_dimension_checked(dimension_checked);
extern void free_dimension_checked(dimension_checked);
extern dimension_checked check_dimension_checked(dimension_checked);
extern bool dimension_checked_consistent_p(dimension_checked);
extern bool dimension_checked_defined_p(dimension_checked);
#define gen_DIMENSION_CHECKED_cons gen_dimension_checked_cons
extern list gen_dimension_checked_cons(dimension_checked, list);
extern void dimension_checked_assign_contents(dimension_checked, dimension_checked);
extern void dimension_checked_non_recursive_free(dimension_checked);
extern void write_dimension_checked(FILE*, dimension_checked);
extern dimension_checked read_dimension_checked(FILE*);
extern dimension_checked make_dimension_checked(intptr_t, bool, bool);

struct _newgen_struct_dimension_checked_ {
  intptr_t _type_;
  intptr_t _dimension_checked_dim_; /* dim:int */
  gen_chunk _dimension_checked_lower_; /* lower:bool */
  gen_chunk _dimension_checked_upper_; /* upper:bool */
};

#define dimension_checked_domain_number(x) ((x)->_type_)
#define dimension_checked_dim_(x) dimension_checked_dim(x) /* old hack compatible */
#define dimension_checked_dim(x) ((x)->_dimension_checked_dim_)
#define dimension_checked_lower_(x) dimension_checked_lower(x) /* old hack compatible */
#define dimension_checked_lower(x) ((x)->_dimension_checked_lower_.b)
#define dimension_checked_upper_(x) dimension_checked_upper(x) /* old hack compatible */
#define dimension_checked_upper(x) ((x)->_dimension_checked_upper_.b)

#define abc_private_spec "\
--NEWGEN-START 171\n\
import entity from \"ri.newgen\";\n\
abc_checked = list:array_dimension_checked*;\n\
array_dimension_checked = array:entity x dims:dimension_checked*;\n\
dimension_checked = dim:int x lower:bool x upper:bool;\n\
"
#endif
