#ifndef _newgen_interval_graph_included
#define _newgen_interval_graph_included
#define _gen_interval_graph_start 114
/*
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY NEWGEN.
 *
 * PLEASE DO NOT MODIFY IT.
 */

#if !defined(_newgen_control_domain_defined_)
#define _newgen_control_domain_defined_
#define CONTROL_NEWGEN_DOMAIN (control_domain)
#define control_NEWGEN_DOMAIN (control_domain)
typedef struct _newgen_struct_control_ * control;
#endif /* _newgen_control_domain_defined_ */

#define interval_vertex_label_domain (_gen_interval_graph_start+0)
#if !defined(_newgen_interval_vertex_label_domain_defined_)
#define _newgen_interval_vertex_label_domain_defined_
#define INTERVAL_VERTEX_LABEL_NEWGEN_DOMAIN (interval_vertex_label_domain)
#define interval_vertex_label_NEWGEN_DOMAIN (interval_vertex_label_domain)
typedef struct _newgen_struct_interval_vertex_label_ * interval_vertex_label;
#endif /* _newgen_interval_vertex_label_domain_defined_ */

/* INTERVAL_VERTEX_LABEL
 */
#define INTERVAL_VERTEX_LABEL(x) ((interval_vertex_label)((x).p))
#define interval_vertex_label_CAST(x) INTERVAL_VERTEX_LABEL(x)
#define INTERVAL_VERTEX_LABEL_CAST(x) INTERVAL_VERTEX_LABEL(x)
#define INTERVAL_VERTEX_LABEL_(x) ((x).e)
#define INTERVAL_VERTEX_LABEL_TYPE interval_vertex_label
#define interval_vertex_label_TYPE interval_vertex_label
#define interval_vertex_label_undefined ((interval_vertex_label)gen_chunk_undefined)
#define interval_vertex_label_undefined_p(x) ((x)==interval_vertex_label_undefined)

extern interval_vertex_label copy_interval_vertex_label(interval_vertex_label);
extern void free_interval_vertex_label(interval_vertex_label);
extern interval_vertex_label check_interval_vertex_label(interval_vertex_label);
extern bool interval_vertex_label_consistent_p(interval_vertex_label);
extern bool interval_vertex_label_defined_p(interval_vertex_label);
#define gen_INTERVAL_VERTEX_LABEL_cons gen_interval_vertex_label_cons
extern list gen_interval_vertex_label_cons(interval_vertex_label, list);
extern void interval_vertex_label_assign_contents(interval_vertex_label, interval_vertex_label);
extern void interval_vertex_label_non_recursive_free(interval_vertex_label);
extern void write_interval_vertex_label(FILE*, interval_vertex_label);
extern interval_vertex_label read_interval_vertex_label(FILE*);
extern interval_vertex_label make_interval_vertex_label(list);

struct _newgen_struct_interval_vertex_label_ {
  intptr_t _type_;
  list _interval_vertex_label_holder_;
};

#define interval_vertex_label_domain_number(x) ((x)->_type_)
#define interval_vertex_label_controls(x) ((x)->_interval_vertex_label_holder_)

#define interval_graph_spec "\
--NEWGEN-START 114\n\
import control from \"ri.newgen\";\n\
interval_vertex_label = controls:control*;\n\
"
#endif
