#ifndef _newgen_tiling_included
#define _newgen_tiling_included
#define _gen_tiling_start 87
/*
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY NEWGEN.
 *
 * PLEASE DO NOT MODIFY IT.
 */

#if !defined(_newgen_Pvecteur_domain_defined_)
#define _newgen_Pvecteur_domain_defined_
#define newgen_Pvecteur(p) (p) /* old hack compatible */
#define PVECTEUR_NEWGEN_EXTERNAL (_gen_tiling_start+0)
#define PVECTEUR_NEWGEN_DOMAIN (PVECTEUR_NEWGEN_EXTERNAL)
#define Pvecteur_NEWGEN_DOMAIN (PVECTEUR_NEWGEN_EXTERNAL)
#endif /* _newgen_Pvecteur_domain_defined_ */

#if !defined(_newgen_matrice_domain_defined_)
#define _newgen_matrice_domain_defined_
#define newgen_matrice(p) (p) /* old hack compatible */
#define MATRICE_NEWGEN_EXTERNAL (_gen_tiling_start+1)
#define MATRICE_NEWGEN_DOMAIN (MATRICE_NEWGEN_EXTERNAL)
#define matrice_NEWGEN_DOMAIN (MATRICE_NEWGEN_EXTERNAL)
#endif /* _newgen_matrice_domain_defined_ */

#define tiling_domain (_gen_tiling_start+2)
#if !defined(_newgen_tiling_domain_defined_)
#define _newgen_tiling_domain_defined_
#define TILING_NEWGEN_DOMAIN (tiling_domain)
#define tiling_NEWGEN_DOMAIN (tiling_domain)
typedef struct _newgen_struct_tiling_ * tiling;
#endif /* _newgen_tiling_domain_defined_ */



/* TILING
 */
#define TILING(x) ((tiling)((x).p))
#define tiling_CAST(x) TILING(x)
#define TILING_CAST(x) TILING(x)
#define TILING_(x) ((x).e)
#define TILING_TYPE tiling
#define tiling_TYPE tiling
#define tiling_undefined ((tiling)gen_chunk_undefined)
#define tiling_undefined_p(x) ((x)==tiling_undefined)

extern tiling copy_tiling(tiling);
extern void free_tiling(tiling);
extern tiling check_tiling(tiling);
extern bool tiling_consistent_p(tiling);
extern bool tiling_defined_p(tiling);
#define gen_TILING_cons gen_tiling_cons
extern list gen_tiling_cons(tiling, list);
extern void tiling_assign_contents(tiling, tiling);
extern void tiling_non_recursive_free(tiling);
extern void write_tiling(FILE*, tiling);
extern tiling read_tiling(FILE*);
extern tiling make_tiling(matrice, Pvecteur);

struct _newgen_struct_tiling_ {
  intptr_t _type_;
  matrice _tiling_tile_; /* tile:matrice */
  Pvecteur _tiling_origin_; /* origin:Pvecteur */
};

#define tiling_domain_number(x) ((x)->_type_)
#define tiling_tile_(x) tiling_tile(x) /* old hack compatible */
#define tiling_tile(x) ((x)->_tiling_tile_)
#define tiling_origin_(x) tiling_origin(x) /* old hack compatible */
#define tiling_origin(x) ((x)->_tiling_origin_)

#define tiling_spec "\
--NEWGEN-START 87\n\
external Pvecteur;\n\
external matrice;\n\
tiling = tile:matrice x origin:Pvecteur;\n\
"
#endif
