/* Test case by Corinne Ancourt
 *
 * Bug: p.N1 not analyzed in main, probably because it is a global
 * variable hidden by an anywhere read/write effect generated by the
 * call to tfile and the use of File * pointer fichier. But the
 * current version of tpips attempts to analyze the assignment "p.N1 =
 * 256;".
 */

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

typedef struct
{
  int N1;
  int N2;
} globalstruct;

globalstruct p;

void init()
{
  assert(p.N1 <= 256 && p.N1>=0);
  assert(p.N2 <= 192 && p.N2>=0);
}

void tfile(int x, char * filename)
{
  FILE *fichier;
  fichier = fopen(filename, "r");
  if (fichier) {
    float val1=0.;
    fclose(fichier);
  }
}

int main(int argc, char* argv[])
{
  p.N1 = 256;
  p.N2 = 192;
  tfile(p.N2,"foo.txt");
  return (0);
}

