# $Id: Makefile 5188 2011-12-31 09:49:52Z coelho $

PARALLEL_VALIDATION = 1
include ../validate.mk

clean: local-clean
local-clean:
	$(RM) test.c threshold-sse.c threshold0 threshold1 filtre0 filtre1
	$(RM) -r coremark.tmpdir
