ROOT = ../../../../..

F.c = impl/simpleExampleBroker/stub/simpleExampleDynamicLoadedFunction.c

INSTALL_RTM	= $(F.c)

PROJECT	= pips
include $(ROOT)/makes/main.mk

# must be consistent with pypsconfig
RTM.d := $(SHR.d)/pyps/broker/simpleExampleBroker/stub
