//
//     This module was automatically generated by PIPS and should
//     be updated by the user with READ and WRITE effects on
//     formal parameters to be useful...
//
int flgr_get_type_string(enum {FLGR_INT8, FLGR_BIT, FLGR_INT16, FLGR_INT32, FLGR_FLOAT32, FLGR_UINT8, FLGR_UINT16, FLGR_UINT32, FLGR_FLOAT64} f1)
{}
