
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer splitc__create_buffer
#define yy_delete_buffer splitc__delete_buffer
#define yy_flex_debug splitc__flex_debug
#define yy_init_buffer splitc__init_buffer
#define yy_flush_buffer splitc__flush_buffer
#define yy_load_buffer_state splitc__load_buffer_state
#define yy_switch_to_buffer splitc__switch_to_buffer
#define yyin splitc_in
#define yyleng splitc_leng
#define yylex splitc_lex
#define yylineno splitc_lineno
#define yyout splitc_out
#define yyrestart splitc_restart
#define yytext splitc_text
#define yywrap splitc_wrap
#define yyalloc splitc_alloc
#define yyrealloc splitc_realloc
#define yyfree splitc_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 36
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE splitc_restart(splitc_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t splitc_leng;

extern FILE *splitc_in, *splitc_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE splitc_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-splitc_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < splitc_leng; ++yyl )\
                    if ( splitc_text[yyl] == '\n' )\
                        --splitc_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up splitc_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up splitc_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via splitc_restart()), so that the user can continue scanning by
	 * just pointing splitc_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when splitc_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t splitc_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow splitc_wrap()'s to do buffer switches
 * instead of setting up a fresh splitc_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void splitc_restart (FILE *input_file  );
void splitc__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE splitc__create_buffer (FILE *file,int size  );
void splitc__delete_buffer (YY_BUFFER_STATE b  );
void splitc__flush_buffer (YY_BUFFER_STATE b  );
void splitc_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void splitc_pop_buffer_state (void );

static void splitc_ensure_buffer_stack (void );
static void splitc__load_buffer_state (void );
static void splitc__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER splitc__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE splitc__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE splitc__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE splitc__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *splitc_alloc (yy_size_t  );
void *splitc_realloc (void *,yy_size_t  );
void splitc_free (void *  );

#define yy_new_buffer splitc__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        splitc_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            splitc__create_buffer(splitc_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        splitc_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            splitc__create_buffer(splitc_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *splitc_in , *splitc_out ;

typedef int yy_state_type;

extern int splitc_lineno;

int splitc_lineno = 1;

extern char *splitc_text;
#define yytext_ptr splitc_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up splitc_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	splitc_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[271] =
    {   0,
        0,    0,   73,   71,    4,    3,   44,   71,   43,   47,
       71,   57,   58,   41,   39,   60,   40,   61,   42,   14,
       14,   51,   59,   34,   33,   35,   50,   70,   70,   55,
       56,   49,   70,   70,   53,   48,   54,   52,    2,   30,
        0,    0,    8,    0,   21,   45,   23,    0,    0,   19,
       36,   17,   37,   18,   38,    0,   10,    0,    1,   20,
       10,   13,   14,    0,   14,   14,    0,   14,   27,   31,
       29,   32,   28,   70,    0,    0,   24,   70,   70,   70,
       22,   46,    2,    2,    0,    6,    0,    0,    0,    0,
       16,    0,   10,   11,    0,    0,    1,    1,    1,    0,

       13,   13,   13,    0,   10,   14,   14,   14,   14,    0,
       12,   25,   26,    0,    9,    0,    0,    0,   70,   70,
       70,   70,   70,   70,   70,    0,    0,    0,    0,    0,
        0,   10,   11,    0,   10,   13,   13,   13,   13,   14,
        0,   12,   12,    0,   12,   12,    7,    0,    0,    0,
        0,   70,   70,   70,   70,   70,   70,   70,   70,    0,
        0,    0,    0,    0,   13,    0,    0,   12,   12,    0,
        0,   10,   12,   12,    0,    0,    0,    0,   70,   63,
       70,   70,   70,   70,   70,   70,   15,    0,    0,    0,
       10,    0,   10,   10,   10,    0,   10,    0,   10,   12,

        0,    0,    0,    0,   70,   70,   70,   70,   70,   70,
       62,    0,    0,    0,   10,    0,    0,   10,    0,    0,
        0,    0,    0,    0,    0,    5,   70,   70,   70,   70,
       70,    0,    0,   10,    0,   10,    0,    0,    0,    0,
       70,   70,   67,   70,   70,    0,    0,    0,   70,   70,
       70,   70,   64,    0,    0,    0,   70,   70,   68,   69,
        0,    0,   70,   70,    0,   70,   70,   65,   66,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   32,
       30,   30,   30,   30,   33,   30,   30,   34,   30,   30,
       35,   36,   37,   38,   39,    1,   40,   41,   27,   42,

       43,   44,   45,   30,   46,   47,   30,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   30,   59,
       30,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    7,
        1,    1,    1,    1,    1,    3,    7,    7,    7,    8,
        9,    9,   10,    8,    1,    3,    1,    1,    8,    6,
        6,    7,    7,    6,    8,    8,    8,    9,    8,   11,
        8,    9,    8,   11,    8,   11,   10,   11,   11,    8,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[316] =
    {   0,
        0,  571,  575,  795,  795,  795,   41,   61,  547,   59,
      534,  795,  795,  541,   55,  795,   56,   54,   65,   82,
       69,  795,  795,   52,  540,   60,  795,    0,   81,  795,
      795,  539,   60,  512,  795,   45,  795,  795,  520,  795,
      498,   73,  795,    0,  795,  795,  795,  544,   86,  795,
      795,  795,  795,  795,  795,  530,  128,  533,   88,  795,
       65,  161,    0,  114,  107,  135,  527,  154,  516,  795,
      795,  795,  500,    0,   90,  486,  795,  466,  145,  455,
      795,  795,  476,  108,  462,  795,  103,    0,    0,    0,
      795,  195,   71,  176,  493,  119,  117,  795,  466,  208,

      201,  209,  203,  142,  230,  237,  126,  238,  219,    0,
      240,  795,  795,  101,  795,    0,  492,  265,  449,  112,
      426,  434,  431,  436,  431,  409,  177,    0,    0,  449,
      223,  271,  795,  267,  285,  280,  283,  311,  293,  312,
      141,  314,  317,  345,  153,  277,  795,  334,    0,    0,
        0,  407,  402,  393,  384,  387,  389,  385,  370,  416,
      407,    0,    0,  402,  340,  357,  366,  165,  795,  371,
      374,  379,  378,  356,  387,    0,    0,  394,  339,    0,
      328,  337,  332,  323,  321,  323,  795,    0,    0,  382,
      399,  395,  413,  444,  202,  435,  450,  451,  470,  795,

      350,    0,    0,  348,  311,  303,  294,  288,  292,  274,
        0,    0,  303,  491,  490,  510,  419,  513,  519,  413,
      523,  452,    0,    0,  298,    0,  265,  246,  252,  251,
      227,    0,  451,  549,  530,  554,  498,    0,  270,  266,
      211,  218,  224,  216,  183,    0,    0,  229,  177,  165,
      173,  167,    0,    0,    0,  190,  147,  115,    0,    0,
        0,  149,  116,  113,  140,   75,   57,    0,    0,  795,
      602,  613,  619,  630,  639,  650,  661,  668,  675,  686,
      692,  694,  696,  698,  701,  709,  715,  717,  721,  723,
      725,  727,  729,  731,  733,  735,  739,  741,  743,  745,

      747,  751,  753,  755,  757,  761,  763,  765,  769,  771,
      773,  777,  779,  783,  787
    } ;

static yyconst flex_int16_t yy_def[316] =
    {   0,
      270,    1,  270,  270,  270,  270,  270,  271,  270,  270,
      272,  270,  270,  270,  270,  270,  270,  270,  270,  270,
       20,  270,  270,  270,  270,  270,  270,  273,  273,  270,
      270,  270,  273,  273,  270,  270,  270,  270,  274,  270,
      270,  271,  270,  271,  270,  270,  270,  270,  275,  270,
      270,  270,  270,  270,  270,  270,  270,  276,  277,  270,
       57,  270,   21,  270,  270,  270,  278,  270,  270,  270,
      270,  270,  270,  273,  279,  280,  270,  273,  273,  273,
      270,  270,  274,  274,  270,  270,  270,  281,  282,  283,
      270,  270,  270,  270,  276,  276,  277,  270,  277,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  284,
      285,  270,  270,  279,  270,  279,  270,  286,  273,  273,
      273,  273,  273,  273,  273,  270,  270,  287,  288,  289,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      284,  285,  270,  270,  270,  270,  270,  270,  290,  291,
      292,  273,  273,  273,  273,  273,  273,  273,  273,  270,
      270,  293,  294,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  295,  296,  297,  273,  273,
      273,  273,  273,  273,  273,  273,  270,  298,  299,  270,
      270,  270,  270,  270,  194,  270,  270,  270,  270,  270,

      270,  300,  301,  302,  273,  273,  273,  273,  273,  273,
      273,  303,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  304,  305,  306,  273,  273,  273,  273,  273,
      273,  307,  270,  270,  270,  270,  270,  308,  270,  309,
      273,  273,  273,  273,  273,  310,  311,  312,  273,  273,
      273,  273,  273,  299,  313,  314,  273,  273,  273,  273,
      305,  315,  273,  273,  270,  273,  273,  273,  273,    0,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270
    } ;

static yyconst flex_int16_t yy_nxt[860] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       29,   28,   28,   28,   30,    4,   31,   32,   33,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   34,   28,   28,   28,   28,   28,
       35,   36,   37,   38,   40,   43,   46,   51,   81,   56,
       53,   57,   57,   57,   69,   70,   58,   43,   52,   54,
       55,   59,   47,   72,   73,   75,   63,   63,   60,   76,
       98,   78,  100,   41,  115,  269,   44,   61,   79,   62,

       62,   63,  270,   87,   87,  115,   82,  100,   44,   64,
       83,   86,   65,  268,   66,   67,  133,  133,   88,   98,
      127,  127,   61,   99,   64,  116,  104,  270,  104,   68,
       96,  105,  105,  105,   64,   98,  116,  106,   66,  107,
       67,   61,   89,   84,   90,   57,   57,   57,  147,   64,
       61,  267,   99,   64,  266,   92,   93,  147,   93,  105,
      105,  105,   64,  107,  264,  108,  153,  154,   64,   61,
       92,   93,  166,   94,   94,   93,   61,   64,   62,   62,
       63,   64,  109,  173,  120,   86,  107,  121,   64,  263,
      122,  101,  166,  102,  161,  161,   64,  169,  147,  123,

      174,  106,  124,   64,  133,  260,  133,  131,  103,  131,
      107,  259,  132,  132,  132,  258,   61,  102,   61,  133,
      134,  169,  134,  133,   61,  135,  135,  135,   64,  216,
       64,  136,  257,  137,   61,  137,   64,  147,  253,  138,
      132,  132,  132,   64,  216,   64,   64,  105,  105,  105,
      136,   64,   61,   61,  252,  110,  139,  137,   93,  137,
       93,   64,  251,  250,   64,   64,  140,  249,  140,  107,
      143,  144,  145,   93,  147,   94,   94,   93,  147,   64,
       64,  245,  148,  148,  135,  135,  135,  146,  132,  132,
      132,  144,  244,  107,  243,   61,  145,  149,   61,   93,

      242,   93,  135,  135,  135,  241,  147,   64,   61,  169,
       64,   86,  137,   93,   93,   93,   94,   94,   93,  231,
       64,  150,   64,  151,  168,   64,   61,   61,   93,  110,
       94,   94,   93,  169,  230,   64,  137,  229,   64,   64,
      165,  165,  147,  228,  143,  167,  145,  168,  227,  169,
      226,  175,  175,   64,   64,   61,  147,  170,  147,  170,
      171,  146,  172,  172,  172,  167,  211,   64,  210,  190,
      145,  190,  209,  169,  191,  191,  191,  208,  192,  207,
      192,  206,   64,  193,  193,  193,  171,  205,  172,  172,
      172,  194,  194,  194,  195,  147,  172,  172,  172,  191,

      191,  191,  147,  200,  201,  201,  196,   93,  200,  197,
       86,  198,  193,  193,  193,   86,  191,  191,  191,  187,
      186,  196,   93,  185,   94,   94,  199,   93,  195,   93,
      193,  193,  193,  184,  183,  198,  218,  218,  218,  182,
      196,   93,   93,   93,   94,   94,   93,  217,  181,  217,
      180,  179,  218,  218,  218,  196,   93,   86,   94,   94,
       93,  194,  194,  194,  160,  195,  195,  195,  234,  234,
      234,  214,  215,  159,  215,  158,  157,  196,  196,  196,
      219,  221,  220,  156,  155,  195,  214,  215,  152,   94,
       94,  215,  196,  196,  196,  133,  133,  196,  222,  237,

      147,   99,  220,  233,   96,  233,  220,  126,  234,  234,
      234,   84,  196,  195,  125,  133,  133,  219,   93,  119,
       93,  118,  235,  113,  235,  196,  220,  236,  236,  236,
      218,  218,  218,   93,  195,   94,   94,   93,  195,  112,
      196,  215,  110,  215,   96,   91,  196,  236,  236,  236,
      196,  220,   86,  237,   85,   84,  215,   80,   94,   94,
      215,  196,   77,   71,   50,  196,  234,  234,  234,   49,
       45,  236,  236,  236,  270,  220,   39,  215,  270,  215,
      270,  270,  215,  270,  215,  270,  270,  270,  270,  270,
      270,  270,  215,  270,   94,   94,  215,  215,  270,   94,

       94,  215,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   74,   74,   74,   74,   74,   74,
       83,  270,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   48,   48,  270,   48,  270,  270,  270,   48,   48,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,  111,  111,  111,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  128,  128,  129,

      129,  130,  130,  141,  141,  142,  142,  142,  270,  142,
      142,  117,  117,  270,  117,  270,  270,  270,  117,  117,
      162,  162,  163,  163,  164,  270,  164,  164,  176,  176,
      177,  177,  178,  178,  188,  188,  189,  189,  202,  202,
      203,  203,  204,  270,  204,  204,  212,  212,  213,  213,
      223,  223,  224,  224,  225,  270,  225,  225,  232,  232,
      238,  238,  239,  239,  240,  270,  240,  240,  246,  246,
      247,  247,  248,  270,  248,  248,  254,  254,  255,  255,
      256,  270,  256,  256,  261,  261,  262,  270,  262,  262,
      265,  270,  265,  265,    3,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270
    } ;

static yyconst flex_int16_t yy_chk[860] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    8,   10,   15,   36,   18,
       17,   18,   18,   18,   24,   24,   19,   42,   15,   17,
       17,   19,   10,   26,   26,   29,   21,   21,   19,   29,
       59,   33,   61,    7,   75,  267,    8,   20,   33,   20,

       20,   20,   21,   49,   49,  114,   36,   61,   42,   20,
       84,   87,   20,  266,   20,   20,   93,   93,   49,   97,
       87,   87,   65,   59,   20,   75,   64,   21,   64,   20,
       96,   64,   64,   64,   65,   96,  114,   65,   20,   65,
       20,  107,   49,   84,   49,   57,   57,   57,  265,   65,
       66,  264,   97,  107,  263,   57,   57,  262,   57,  104,
      104,  104,   66,   65,  258,   66,  120,  120,  107,   68,
       57,   57,  141,   57,   57,   57,   62,   66,   62,   62,
       62,   68,   66,  145,   79,  127,   68,   79,   62,  257,
       79,   62,  141,   62,  127,  127,   68,  168,  256,   79,

      145,   68,   79,   62,   94,  252,   94,   92,   62,   92,
       68,  251,   92,   92,   92,  250,  101,   62,  103,   94,
      100,  168,  100,   94,  102,  100,  100,  100,  101,  195,
      103,  101,  249,  101,  109,  103,  102,  248,  245,  102,
      131,  131,  131,  101,  195,  103,  109,  105,  105,  105,
      103,  102,  106,  108,  244,  111,  102,  101,  105,  103,
      105,  109,  243,  242,  106,  108,  109,  241,  108,  106,
      111,  111,  111,  105,  240,  105,  105,  105,  239,  106,
      108,  231,  118,  118,  134,  134,  134,  111,  132,  132,
      132,  111,  230,  106,  229,  136,  111,  118,  137,  132,

      228,  132,  135,  135,  135,  227,  225,  136,  139,  146,
      137,  213,  136,  135,  132,  135,  132,  132,  132,  210,
      139,  118,  136,  118,  146,  137,  138,  140,  135,  142,
      135,  135,  135,  146,  209,  139,  136,  208,  138,  140,
      139,  138,  148,  207,  142,  142,  142,  143,  206,  143,
      205,  148,  148,  138,  140,  165,  204,  144,  201,  144,
      144,  142,  144,  144,  144,  142,  186,  165,  185,  166,
      142,  166,  184,  143,  166,  166,  166,  183,  167,  182,
      167,  181,  165,  167,  167,  167,  170,  179,  170,  170,
      170,  171,  171,  171,  172,  175,  172,  172,  172,  190,

      190,  190,  178,  174,  175,  175,  172,  172,  173,  172,
      164,  172,  192,  192,  192,  161,  191,  191,  191,  160,
      159,  172,  172,  158,  172,  172,  172,  191,  220,  191,
      193,  193,  193,  157,  156,  172,  217,  217,  217,  155,
      220,  193,  191,  193,  191,  191,  191,  196,  154,  196,
      153,  152,  196,  196,  196,  220,  193,  130,  193,  193,
      193,  194,  194,  194,  126,  197,  198,  222,  233,  233,
      233,  194,  194,  125,  194,  124,  123,  197,  198,  222,
      197,  198,  197,  122,  121,  199,  194,  194,  119,  194,
      194,  194,  197,  198,  222,  197,  197,  199,  198,  222,

      117,   99,  199,  214,   95,  214,  197,   85,  214,  214,
      214,   83,  199,  237,   80,  199,  199,  199,  215,   78,
      215,   76,  216,   73,  216,  237,  199,  216,  216,  216,
      218,  218,  218,  215,  219,  215,  215,  215,  221,   69,
      237,  218,   67,  218,   58,   56,  219,  235,  235,  235,
      221,  219,   48,  221,   41,   39,  218,   34,  218,  218,
      218,  219,   32,   25,   14,  221,  234,  234,  234,   11,
        9,  236,  236,  236,    3,  219,    2,  234,    0,  234,
        0,    0,  236,    0,  236,    0,    0,    0,    0,    0,
        0,    0,  234,    0,  234,  234,  234,  236,    0,  236,

      236,  236,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  273,  273,  273,  273,  273,  273,
      274,    0,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  275,  275,    0,  275,    0,    0,    0,  275,  275,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  278,  278,  278,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  281,  281,  282,

      282,  283,  283,  284,  284,  285,  285,  285,    0,  285,
      285,  286,  286,    0,  286,    0,    0,    0,  286,  286,
      287,  287,  288,  288,  289,    0,  289,  289,  290,  290,
      291,  291,  292,  292,  293,  293,  294,  294,  295,  295,
      296,  296,  297,    0,  297,  297,  298,  298,  299,  299,
      300,  300,  301,  301,  302,    0,  302,  302,  303,  303,
      304,  304,  305,  305,  306,    0,  306,  306,  307,  307,
      308,  308,  309,    0,  309,  309,  310,  310,  311,  311,
      312,    0,  312,  312,  313,  313,  314,    0,  314,  314,
      315,    0,  315,  315,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[73] =
    {   0,
1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int splitc__flex_debug;
int splitc__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *splitc_text;
#line 1 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
/* $Id: lexer.l 23128 2016-07-01 11:58:21Z coelho $ */
/******************** LEXICAL ANALYZER **************************

  Here are the lexical rules, based on the work of people from
  Open Source Quality projects (http://osq.cs.berkeley.edu/), used
  by the CCured source-to-source translator for C


*****************************************************************/
/*(*
 *
 * Copyright (c) 2001-2003,
 *  George C. Necula    <necula@cs.berkeley.edu>
 *  Scott McPeak        <smcpeak@cs.berkeley.edu>
 *  Wes Weimer          <weimer@cs.berkeley.edu>
 *  Ben Liblit          <liblit@cs.berkeley.edu>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 *
 * 3. The names of the contributors may not be used to endorse or promote
 * products derived from this software without specific prior written
 * permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *)
(* FrontC -- lexical analyzer
**
** 1.0	3.22.99	Hugues Cassé	First version.
** 2.0  George Necula 12/12/00: Many extensions
*)*/
#define YY_NO_INPUT 1
#line 58 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
#ifdef HAVE_CONFIG_H
    #include "pips_config.h"
#endif
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>

#include "genC.h"
#include "linear.h"
#include "ri.h"
#include "ri-util.h"
#include "misc.h"

#include "splitc.h"
#include "preprocessor.h"


int csplit_line_number = 1; /**< To be exported to the parser for
				splitting the preprocessed file */
int user_line_number = 1; /**< To be exported to the parser for error
			      messages related to the user file */

/* To track current file position: */
#define YY_USER_ACTION update_csplit_file_offset_information();
size_t current_csplit_file_offset = 0;
size_t csplit_file_offset_beginning = 0;

/* To track nesting in brackets */
static int bracket_depth = 0;

/* A state-machine to gather the trailing comments of a statement with an
   heuristic to decide if some comments and spaces will go into the
   previous or next top-level construct: */
enum gather_comment_state_t {
  PUT_IN_NEXT_TOP_LEVEL_CONSTRUCT, /**< Normal mode: comments and spaces
				     are associated to the top-level
				     construct to encounter: */
  GATHER_SPACES, /**< We gather only spaces in the previous top-level
		    construct */
  GATHER_COMMENT, /**< We gather comments in the previous top-level construct */
};
/* Indeed it does not work since csplit_copy() is called from splitc.y
   when a function definition is found and thus we cannot gather the
   comment in it... :-( */
enum gather_comment_state_t
  gather_comment_state_machine = PUT_IN_NEXT_TOP_LEVEL_CONSTRUCT;


static void gdb_marker()
{
/* Just to be able to set an easy breakpoint */
;
}


/* Reinitialise global position numbers for a new file. */
void reset_csplit_line_number()
{
  csplit_line_number = 1;
  user_line_number = 1;
  current_csplit_file_offset = 0;
  csplit_file_offset_beginning = 0;
  gather_comment_state_machine = PUT_IN_NEXT_TOP_LEVEL_CONSTRUCT;
  bracket_depth = 0;
}

static int csplit_current_beginning = 1000000;
static int user_current_beginning = 1000000;


/* If we encounter a possible function begin, just snapshot the position
   of the function beginning: */
static void update_csplit_current_beginning() {
  user_current_beginning = csplit_current_beginning > csplit_line_number?
    user_line_number : user_current_beginning;
  csplit_current_beginning = csplit_current_beginning > csplit_line_number?
    csplit_line_number : csplit_current_beginning;
  /* From now, the comments and spaces are associated to the current
     top-level construct: */
  gather_comment_state_machine = PUT_IN_NEXT_TOP_LEVEL_CONSTRUCT;
}


/* This function is called at the end of any top-level C construct: */
void reset_csplit_current_beginning()
{
  int leaked = 0;

  csplit_current_beginning = 1000000;
  user_current_beginning = 1000000;
  csplit_is_static_p = false;

  /* Snapshot the current file position as a potential function begin: */
  csplit_file_offset_beginning = current_csplit_file_offset;

  /* Aggregate following spaces and comments on the sameline to the
     previous top-level construct: */
  gather_comment_state_machine = GATHER_COMMENT;


  if(!string_undefined_p(csplit_current_function_name))
    free(csplit_current_function_name);
  csplit_current_function_name = string_undefined;

  if(!string_undefined_p(csplit_current_function_name2))
    free(csplit_current_function_name2);
  csplit_current_function_name2 = string_undefined;

  if(!string_undefined_p(csplit_definite_function_name))
    free(csplit_definite_function_name);
  csplit_definite_function_name = string_undefined;

  if(!string_undefined_p(csplit_definite_function_signature))
    free(csplit_definite_function_signature);
  csplit_definite_function_signature = string_undefined;

  if((leaked=check_signature_balance())!=0) {
    /* FI: I'm not ready to abort() here... */
    pips_debug(5, "Likely memory leaks: %d\n", leaked);
  }
}

int get_csplit_current_beginning()
{
  return csplit_current_beginning;
}


/* Get the current line number in the file to split from the user point of
   view (before preprocessor expansion): */
int get_user_current_beginning() {
  return user_current_beginning;
}


/* Get the file position in the file to split where the current function
   begins: */
size_t get_csplit_file_offset_beginning() {
  return csplit_file_offset_beginning;
}


/* Get the current file position in the file to split: */
size_t get_current_csplit_file_offset() {
  return current_csplit_file_offset;
}


/* Function called each time a token is read to trac file position
   information: */
void update_csplit_file_offset_information() {
  current_csplit_file_offset += splitc_leng;
}


static int lf_count(string s)
{
  string cs = s;
  int count = 0;

  while(*cs) {
    if(*cs=='\n') count++;
    cs++;
  }
  return count;
}

/* The lexer cannot handle the ambiguity between named types and
 *variables without extra-help. 
 */

#define TOKEN_UNDEFINED (-1)
static int previous_keyword_token = TOKEN_UNDEFINED;

/* This is going to be the previous token because LEXER_RETURN is not
used in case the lexer handles either a named type or a variable. */
#define LEXER_RETURN(t) return(previous_keyword_token=t)

/* See if id is a keyword, a typedef or an identifier.
 * Returns the token number for keywords and typedefs.
 * Returns 0 for variable identifiers.
 */
static int is_c_preprocessor_keyword_typedef(char * id)
{
  /* No need to bother for scopes when dealing with C keywords,
   * but do not take into account top-level typedefs which may be masked.
   */
  int t = is_c_keyword_typedef(id);
  if(t==0 || t==TK_NAMED_TYPE) {
    // id may be a keyword, but scopes must be used
    string sn = get_preprocessor_current_scope();
    string scoped_id = strdup(concatenate(id, "%", sn, NULL));
    t = is_c_keyword_typedef(scoped_id);
    free(scoped_id);
    if(t == 0) {
      int i, n = preprocessor_scope_number();
      for(i=2; i<=n && t==0; i++) {
	sn = get_preprocessor_nth_scope(i);
	scoped_id = strdup(concatenate(id, "%", sn, NULL));
	t = is_c_keyword_typedef(scoped_id);
	ifdebug(1) {
          if(t==TK_NAMED_TYPE)
            fprintf(stderr, "Token \"%s\" identified as TK_NAMED_TYPE.\n",
			    scoped_id);
        }
	free(scoped_id);
      }
      /* Check again for a global typedef */
      t = is_c_keyword_typedef(id);
    }
  }
  /* FI: we *bet* here that "extern foo(t1, t2, t3);"
   * with t1, t2 and t3 named type is not possible:-(
   */
#define TK_TYPE_P(tk) \
  ((tk)==TK_CHAR || (tk)==TK_INT || \
   (tk)==TK_DOUBLE || (tk)==TK_FLOAT || (tk)==TK_COMPLEX || \
   (tk)==TK_ENUM || (tk)==TK_STRUCT || (tk)==TK_UNION || \
   (tk)==TK_SIGNED|| (tk)==TK_UNSIGNED|| (tk)==TK_LONG|| (tk)==TK_SHORT ||\
   (tk)==TK_RETURN)
  if(t==TK_NAMED_TYPE
     && (TK_TYPE_P(previous_keyword_token)
		  ||previous_keyword_token==TK_NAMED_TYPE)) {
    // Identifier
    t = 0;
    pips_debug(1, "Token \"%s\" is in fact assumed to be an identifier.\n",
		  id);
  }
  previous_keyword_token = t;
  if(t==TK_STATIC && bracket_depth>0)
    t = TK_STATIC_DIMENSION;
  return t;
}

/* To track file line number automatically: */
/* From C norm A.1: */
/* " */
#line 1069 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int splitc_lex_destroy (void );

int splitc_get_debug (void );

void splitc_set_debug (int debug_flag  );

YY_EXTRA_TYPE splitc_get_extra (void );

void splitc_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *splitc_get_in (void );

void splitc_set_in  (FILE * in_str  );

FILE *splitc_get_out (void );

void splitc_set_out  (FILE * out_str  );

yy_size_t splitc_get_leng (void );

char *splitc_get_text (void );

int splitc_get_lineno (void );

void splitc_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int splitc_wrap (void );
#else
extern int splitc_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( splitc_text, splitc_leng, 1, splitc_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( splitc_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( splitc_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, splitc_in))==0 && ferror(splitc_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(splitc_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int splitc_lex (void);

#define YY_DECL int splitc_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after splitc_text and splitc_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( splitc_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(splitc_text[splitc_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 333 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"


#line 1255 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! splitc_in )
			splitc_in = stdin;

		if ( ! splitc_out )
			splitc_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			splitc_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				splitc__create_buffer(splitc_in,YY_BUF_SIZE );
		}

		splitc__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of splitc_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 271 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 795 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < splitc_leng; ++yyl )
				if ( splitc_text[yyl] == '\n' )
					   
    splitc_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 335 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{ // help emacs: */
	 // Bug in the Flex 2.5.35 manual A.4.3, "/***/" fails. :-(
			  csplit_line_number += lf_count(splitc_text);
			  user_line_number += lf_count(splitc_text);


			  pips_debug(5,"Comment \"%s\"\n",splitc_text);

			  if (gather_comment_state_machine == GATHER_COMMENT)
			    /* This comment is associated to previous
			       top-level construct: */
			    reset_csplit_current_beginning();
			  if (gather_comment_state_machine == GATHER_SPACES)
			    /* We encounter a comment whereas we were
			       gathering spaces into the previous
			       top-level construct. So now this comment
			       will go in the next top-level construct: */
			    gather_comment_state_machine = PUT_IN_NEXT_TOP_LEVEL_CONSTRUCT;
                        }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 355 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                /* Look for a # up to the end of line,
                   dealing with any backslashed new lines: */
                                /* csplit_line_number++; */
                                pips_debug(5,"Pragma comment %s\n",splitc_text);
                                /* Must be a line pragma left by the preprocessor:
                                   # 1 blablabla.c
                                   #pragma blablabla
                                   #line nnn
                                */
                                gdb_marker();
                                size_t n;
                                if(strstr(splitc_text, "#pragma")==splitc_text) {
                                  // FC 2016-06-18: Why not count pragma lines? This just breaks line numbering...
                                  // commented out: user_line_number--;
                                }
                                /* the preprocessor seems to provide line information in pragmas
                                   which are not #line pragmas. */
                                else if(/* strstr(splitc_text, "#line")==splitc_text && */ (n=strlen(splitc_text))>=4) {
                                   int initial_C_line_number = -1;
								   char include_file[n] ;
                                   int items = sscanf(splitc_text+1, "%d \"%[^\"]\"", &initial_C_line_number,include_file);
                                   if(items>=1) {
                                      /* Get rid of the pragma LF itslef */
                                      user_line_number = initial_C_line_number-1;
                                      if(items==2) {
                                        if(!current_file_path) current_file_path = strdup(include_file);
                                        else if(!current_include_file_path) current_include_file_path=strdup(include_file);
                                        else if(strcmp(include_file,current_file_path)==0) { free(current_include_file_path) ; current_include_file_path=NULL; }
                                      }
                                   }
                                   else {
                                      pips_user_warning("No line number in # pragma: \"%s\".\n", splitc_text);
                                      splitc_error("Ill. formated # pragma\n");
                                   }
                                }
                        }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 393 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                          csplit_line_number++;
			  user_line_number++;
			  pips_debug(5, "New line %d, ext=%d, func=%d\n", csplit_line_number, csplit_is_external, csplit_is_function);

			  if (gather_comment_state_machine == GATHER_COMMENT) {
			    /* We encounter a newline, stop gathering
			       comments and gather spaces from now: */
			    //gather_comment_state_machine = GATHER_SPACES;
			    /* Well, ideed, we want to be compatible with
			       old behaviour: associate newlines and other
			       from now to next top-level construct: */
			    gather_comment_state_machine = PUT_IN_NEXT_TOP_LEVEL_CONSTRUCT;
			    /* Associate the current \n to the previous
			       top-level construct: */
			    reset_csplit_current_beginning();
			  }
			  if (gather_comment_state_machine == GATHER_SPACES) {
			    /* Add this newline to the previous top-level
			       construct: */
			     reset_csplit_current_beginning();
			  }
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 417 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                          /* Eat up whitespaces. After the previous '\n'
			     since it includes '\n' and we want
			     lower priority */
			  if (gather_comment_state_machine == GATHER_COMMENT
			      || gather_comment_state_machine == GATHER_SPACES) {
			    /* Add this space to the previous top-level
			       construct: */
			     reset_csplit_current_beginning();
			  }
                        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 429 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                LEXER_RETURN(TK_PRAGMA);
                        }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 433 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
  /* Have a look to Flex A.4.3 too... */
                                /* Escaped character constants. Their
                                   syntax is understood in PIPS character
                                   constant construtors. */
                                pips_debug(9,"TK_CHARCON: %s\n",splitc_text);
                                splitc_lval.string = strdup(splitc_text);
				LEXER_RETURN(TK_CHARCON);
                        }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 443 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                /* Escaped wide character constants. Their
                                   syntax is understood in PIPS character
                                   constant construtors. */
                                pips_debug(9,"TK_CHARCON wide character constant: %s\n",splitc_text);
                                splitc_lval.string = strdup(splitc_text);
				LEXER_RETURN(TK_CHARCON);
                        }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 452 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_debug(5,"TK_STRINGCON regular or wide string: %s\n",splitc_text);
                                /* the "world" in L"Hello, " "world" should be treated as
                                   wide even though there's no L immediately preceding it */
                                splitc_lval.string = strdup(splitc_text);
				LEXER_RETURN(TK_STRINGCON);
                        }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 460 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_debug(5,"TK_WSTRINGCON wide string: %s\n",splitc_text);
                                splitc_lval.string = strdup(splitc_text);
				LEXER_RETURN(TK_WSTRINGCON);
                        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 465 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_debug(5,"TK_FLOATCON %s\n",splitc_text);
                                splitc_lval.string = strdup(splitc_text);
				LEXER_RETURN(TK_FLOATCON);
                        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 470 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_debug(5,"TK_COMPLEXCON %s\n",splitc_text);
                                splitc_lval.string = strdup(splitc_text);
				LEXER_RETURN(TK_COMPLEXCON);
                        }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 475 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_debug(5,"Hexnum TK_INTCON %s\n",splitc_text);
                                splitc_lval.string = strdup(splitc_text);
				LEXER_RETURN(TK_INTCON);
                        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 480 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_debug(5,"Octnum TK_INTCON %s\n",splitc_text);
                                splitc_lval.string = strdup(splitc_text);
				LEXER_RETURN(TK_INTCON);
                        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 485 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_debug(5,"TK_INTCON %s\n",splitc_text);
                                splitc_lval.string = strdup(splitc_text);
				LEXER_RETURN(TK_INTCON);
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 490 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_EOF %s\n",splitc_text);
				yyterminate();
			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 494 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_ELLIPSIS %s\n",splitc_text);
				LEXER_RETURN(TK_ELLIPSIS);
			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 498 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_PLUS_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_PLUS_EQ);
			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 502 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_MINUS_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_MINUS_EQ);
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 506 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_STAR_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_STAR_EQ);
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 510 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_SLASH_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_SLASH_EQ);
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 514 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_PERCENT_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_PERCENT_EQ);
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 518 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_PIPE_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_PIPE_EQ);
			}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 522 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_AND_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_AND_EQ);
			}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 526 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_CIRC_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_CIRC_EQ);
			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 530 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_INF_INF_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_INF_INF_EQ);
			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 534 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_SUP_SUP_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_SUP_SUP_EQ);
			}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 538 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_INF_INF %s\n",splitc_text);
				LEXER_RETURN(TK_INF_INF);
			}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 542 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_SUP_SUP %s\n",splitc_text);
				LEXER_RETURN(TK_SUP_SUP);
			}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 546 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_EQ_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_EQ_EQ);
			}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 550 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_EXCLAM_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_EXCLAM_EQ);
			}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 554 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_INF_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_INF_EQ);
			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 558 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_SUP_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_SUP_EQ);
			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 562 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_EQ %s\n",splitc_text);
				LEXER_RETURN(TK_EQ);
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 566 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_INF %s\n",splitc_text);
				LEXER_RETURN(TK_INF);
			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 570 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_SUP %s\n",splitc_text);
				LEXER_RETURN(TK_SUP);
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 574 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_PLUS_PLUS %s\n",splitc_text);
				LEXER_RETURN(TK_PLUS_PLUS);
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 578 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_MINUS_MINUS %s\n",splitc_text);
				LEXER_RETURN(TK_MINUS_MINUS);
			}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 582 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_ARROW %s\n",splitc_text);
				LEXER_RETURN(TK_ARROW);
			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 586 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_PLUS %s\n",splitc_text);
				LEXER_RETURN(TK_PLUS);
			}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 590 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_MINUS %s\n",splitc_text);
				LEXER_RETURN(TK_MINUS);
			}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 594 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_STAR %s\n",splitc_text);
				LEXER_RETURN(TK_STAR);
			}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 598 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_SLASH %s\n",splitc_text);
				LEXER_RETURN(TK_SLASH);
			}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 602 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_PERCENT %s\n",splitc_text);
				LEXER_RETURN(TK_PERCENT);
			}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 606 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_EXCLAM %s\n",splitc_text);
				LEXER_RETURN(TK_EXCLAM);
			}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 610 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_AND_AND %s\n",splitc_text);
				LEXER_RETURN(TK_AND_AND);
			}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 614 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_PIPE_PIPE %s\n",splitc_text);
				LEXER_RETURN(TK_PIPE_PIPE);
			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 618 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_AND %s\n",splitc_text);
				LEXER_RETURN(TK_AND);
			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 622 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_PIPE %s\n",splitc_text);
				LEXER_RETURN(TK_PIPE);
			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 626 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_CIRC %s\n",splitc_text);
				LEXER_RETURN(TK_CIRC);
			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 630 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_QUEST %s\n",splitc_text);
				LEXER_RETURN(TK_QUEST);
			}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 634 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_COLON %s\n",splitc_text);
				LEXER_RETURN(TK_COLON);
			}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 638 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_TILDE %s\n",splitc_text);
				LEXER_RETURN(TK_TILDE);
			}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 642 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_LBRACE %s\n",splitc_text);
				LEXER_RETURN(TK_LBRACE);
			}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 646 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_RBRACE %s\n",splitc_text);
				LEXER_RETURN(TK_RBRACE);
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 650 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_LBRACKET %s\n",splitc_text);
				bracket_depth++;
				LEXER_RETURN(TK_LBRACKET);
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 655 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_RBRACKET %s\n",splitc_text);
				bracket_depth--;
				LEXER_RETURN(TK_RBRACKET);
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 660 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_LPAREN %s\n",splitc_text);
				LEXER_RETURN(TK_LPAREN);
			}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 664 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_RPAREN %s\n",splitc_text);
				LEXER_RETURN(TK_RPAREN);
			}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 668 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_SEMICOLON %s\n",splitc_text);
				LEXER_RETURN(TK_SEMICOLON);
			}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 672 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_COMMA %s\n",splitc_text);
				LEXER_RETURN(TK_COMMA);
			}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 676 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_DOT %s\n",splitc_text);
				LEXER_RETURN(TK_DOT);
			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 680 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_SIZEOF %s\n",splitc_text);
				LEXER_RETURN(TK_SIZEOF);
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 684 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_ASM %s\n",splitc_text);
				LEXER_RETURN(TK_ASM);
			}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 688 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
	/* convert __va_list from bsd into __builtin_va_list */
	pips_debug(5,"TK_VA_LIST %s\n",splitc_text);
	splitc_text = strdup("__builtin_va_list");
	int t = is_c_preprocessor_keyword_typedef(splitc_text);
	update_csplit_current_beginning();
	pips_assert("builtin valist found\n",t>0);
	pips_debug(5,"Keyword or typedef name: %s\n",splitc_text);
	splitc_lval.string = strdup(splitc_text);
	return (t);
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 699 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{

/* FI: when we change our minds and want to make these tokens, we must
 * insert them in keyword_typedef_table.
 */

				pips_debug(5,"TK_ATTRIBUTE %s\n",splitc_text);
				LEXER_RETURN(TK_ATTRIBUTE);
			}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 708 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_user_warning("gcc extension keyword \"__extension__\" is ignored\n");
                        }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 711 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_user_warning("gcc extension keyword \"__inline\" is ignored\n");
                        }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 714 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_user_warning("gcc extension keyword \"__inline__\" is ignored\n");
                        }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 717 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                pips_user_warning("gcc extension keyword \"__signed__\" is ignored\n");
                        }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 720 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
                                /* C keywords or identifiers */
				int t = is_c_preprocessor_keyword_typedef(splitc_text);
                                update_csplit_current_beginning();
                                if (t>0)
				   {
				       pips_debug(5,"Keyword or typedef name: %s\n",splitc_text);
                                       splitc_lval.string = strdup(splitc_text);
				       return (t);
				   }
				else
				   {
 				       pips_debug(5,"TK_IDENT: %s\n",splitc_text);
                                       /* Might not work if a function returns a struct declared locally in the function declaration, or a pointer to such a structure */
                                       if(string_undefined_p(csplit_current_function_name)) {
					 csplit_current_function_name = strdup(splitc_text);
					 pips_debug(5, "Temptative function name found: \"%s\"\n",
						    csplit_current_function_name);
                                       }
                                       else if(string_undefined_p(csplit_current_function_name2)) {
				         pips_debug(5, "Identifier \"%s\" ignored because of two previous identifiers \"%s\"\n",
						     splitc_text, csplit_current_function_name);
				         csplit_current_function_name2 = strdup(splitc_text);
				       }
				       else {
				         free(csplit_current_function_name2);
					 pips_debug(5, "Identifier \"%s\" not ignored in spite of two previous identifiers \"%s\"\n",
						    splitc_text, csplit_current_function_name);
					 csplit_current_function_name2 = strdup(splitc_text);
				       }

				       splitc_lval.string = strdup(splitc_text);
				       LEXER_RETURN(TK_IDENT);
				   }
			}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 755 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
				pips_debug(5,"TK_EOF %s\n",splitc_text);
				LEXER_RETURN(TK_EOF);
			}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 759 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
{
        if (*splitc_text=='#') {
			    csplit_parser_warning("Unrecognized character '%s'\n", splitc_text);
			    pips_user_warning("Preprocessor directives must have disappeared thanks to the C preprocessor.\n"
"Check the input code and/or modify the preprocessor options using environment variables PIPS_CPP.\n");
        }
				else
			    csplit_parser_warning("Unrecognized character '%s'\n", splitc_text);
			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 768 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"
ECHO;
	YY_BREAK
#line 2073 "<stdout>"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed splitc_in at a new source and called
			 * splitc_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = splitc_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( splitc_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * splitc_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of splitc_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					splitc_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			splitc_restart(splitc_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > (yy_size_t)YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) splitc_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 271 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 271 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 270);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					splitc_restart(splitc_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( splitc_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve splitc_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    splitc_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void splitc_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        splitc_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            splitc__create_buffer(splitc_in,YY_BUF_SIZE );
	}

	splitc__init_buffer(YY_CURRENT_BUFFER,input_file );
	splitc__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void splitc__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		splitc_pop_buffer_state();
	 *		splitc_push_buffer_state(new_buffer);
     */
	splitc_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	splitc__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (splitc_wrap()) processing, but the only time this flag
	 * is looked at is after splitc_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void splitc__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	splitc_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE splitc__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) splitc_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in splitc__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) splitc_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in splitc__create_buffer()" );

	b->yy_is_our_buffer = 1;

	splitc__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with splitc__create_buffer()
 * 
 */
    void splitc__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		splitc_free((void *) b->yy_ch_buf  );

	splitc_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a splitc_restart() or at EOF.
 */
    static void splitc__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	splitc__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then splitc__init_buffer was _probably_
     * called from splitc_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void splitc__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		splitc__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void splitc_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	splitc_ensure_buffer_stack();

	/* This block is copied from splitc__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from splitc__switch_to_buffer. */
	splitc__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void splitc_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	splitc__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		splitc__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void splitc_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)splitc_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in splitc_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)splitc_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in splitc_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE splitc__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) splitc_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in splitc__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	splitc__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to splitc_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       splitc__scan_bytes() instead.
 */
YY_BUFFER_STATE splitc__scan_string (yyconst char * yystr )
{
    
	return splitc__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to splitc_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE splitc__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) splitc_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in splitc__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = splitc__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in splitc__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up splitc_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		splitc_text[splitc_leng] = (yy_hold_char); \
		(yy_c_buf_p) = splitc_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		splitc_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int splitc_get_lineno  (void)
{
        
    return splitc_lineno;
}

/** Get the input stream.
 * 
 */
FILE *splitc_get_in  (void)
{
        return splitc_in;
}

/** Get the output stream.
 * 
 */
FILE *splitc_get_out  (void)
{
        return splitc_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t splitc_get_leng  (void)
{
        return splitc_leng;
}

/** Get the current token.
 * 
 */

char *splitc_get_text  (void)
{
        return splitc_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void splitc_set_lineno (int  line_number )
{
    
    splitc_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see splitc__switch_to_buffer
 */
void splitc_set_in (FILE *  in_str )
{
        splitc_in = in_str ;
}

void splitc_set_out (FILE *  out_str )
{
        splitc_out = out_str ;
}

int splitc_get_debug  (void)
{
        return splitc__flex_debug;
}

void splitc_set_debug (int  bdebug )
{
        splitc__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from splitc_lex_destroy(), so don't allocate here.
     */

    /* We do not touch splitc_lineno unless the option is enabled. */
    splitc_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    splitc_in = stdin;
    splitc_out = stdout;
#else
    splitc_in = (FILE *) 0;
    splitc_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * splitc_lex_init()
     */
    return 0;
}

/* splitc_lex_destroy is for both reentrant and non-reentrant scanners. */
int splitc_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		splitc__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		splitc_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	splitc_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * splitc_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *splitc_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *splitc_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void splitc_free (void * ptr )
{
	free( (char *) ptr );	/* see splitc_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 768 "/home/dounia/MYPIPS/prod/pips/src/Libs/preprocessor/lexer.l"



/* This function is renamed splitc_error(). It should probably reset more variables */
void splitc_error(const char * msg)
{
    /* I should call csplit_parser_error() or the equivalent module */
    string ifn = get_splitc_input_file_name();
    string current_line = safe_read_nth_line(ifn, csplit_line_number);
    /* pips_user_warning(
                 "C %s near \"%s\" at preprocessed line %d (user line %d):\n%s\n\n",
                 msg, splitc_text, csplit_line_number, user_line_number,
		 current_line); */
    pips_user_warning(
                 "C %s near \"%s\" at line %d in file \"%s\":\n%s\n\n",
                 msg, splitc_text, user_line_number,
		 preprocessor_current_initial_file_name,
		 current_line);
    free(current_line);
    pips_user_error("Syntax error detected by PIPS C preprocessor.\n"
		    "Suggestions:\n"
		    " 1. check the legality of the source code with a production C compiler\n"
		    " 2. see if the issue is linked to a non-standard C feature\n"
		    " 3. see if the issue is a C feature unsupported by PIPS C parser\n"
		    " 4. see if the source code can be rewritten differently.\n");
}

#ifndef splitc_wrap
int splitc_wrap() { return 1;}
#endif

